/*
 Navicat Premium Data Transfer

 Source Server         : Mysql_DB
 Source Server Type    : MySQL
 Source Server Version : 100417
 Source Host           : localhost:3306
 Source Schema         : demovku

 Target Server Type    : MySQL
 Target Server Version : 100417
 File Encoding         : 65001

 Date: 13/05/2021 15:48:58
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for table_decuongchitiet
-- ----------------------------
DROP TABLE IF EXISTS `table_decuongchitiet`;
CREATE TABLE `table_decuongchitiet`  (
  `id_decuong` int NOT NULL AUTO_INCREMENT,
  `id_hocphan` int NULL DEFAULT NULL,
  `phanbo_lythuyet` int NULL DEFAULT NULL,
  `phanbo_baitap` int NULL DEFAULT NULL,
  `phanbo_thuchanh` int NULL DEFAULT NULL,
  `phanbo_tuhoc` int NULL DEFAULT NULL,
  `giangvienphutrach_id` int NULL DEFAULT NULL,
  `gv_daycung` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `khoaphutrach` int NULL DEFAULT NULL,
  `id_nganh` int NULL DEFAULT NULL,
  `loaihocphan` int NULL DEFAULT NULL,
  `khoikienthuc` int NULL DEFAULT NULL,
  `mota_tomtat` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
  `muctieu_kienthuc` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
  `muctieu_kynang` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
  `muctieu_thaido` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
  `nhiemvu` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
  `tailieuthamkhao_giaotrinh` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
  `tailieuthamkhao_sach` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
  `ngaypheduyet` int NULL DEFAULT NULL,
  PRIMARY KEY (`id_decuong`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 35 CHARACTER SET = utf8 COLLATE = utf8_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of table_decuongchitiet
-- ----------------------------
INSERT INTO `table_decuongchitiet` VALUES (17, 111, 30, 0, 30, 90, 123, '148', 2, 3, 1, 4, 'Học phần giới thiệu những kiến thức cơ bản về mạng di động, hệ thống cảm biến và sự kết hợp của chúng. Học phần giúp sinh viên hiểu và nâng cao kỹ năng phân tích những vấn đề ràng buộc về năng lượng và tính di động trong việc thiết kế các hệ thống cảm biến di động.', 'Cở sở hạ tầng mạng di động\r\nKiến trúc hệ thống cảm biến\r\nMạng cảm biến không dây\r\nHệ thống cảm biến trên các thiết bị di động\r\nLập trình ứng dụng và mô phỏng trên các hệ thống cảm biến trên các thiết bị di động và mạng cảm biến không dây', 'Rèn luyện cho sinh viên kỹ năng tự nghiên cứu, kỹ năng làm việc nhóm thông qua các hoạt động và bài thực hành', 'Giúp sinh viên hình thành thái độ học tập tích cực, có đạo đức nghề nghiệp, tự chủ, tự chịu trách nhiệm trong giải quyết các vấn đề liên quan', 'Tham gia ít nhất 80% số tiết học của lớp học phần;\r\nTham gia các hoạt động làm việc nhóm theo qui định của lớp học phần;\r\nTự tìm hiểu các vấn đề do giảng viên giao để thực hiện ngoài giờ học trên lớp;\r\nHoàn thành tất cả bài đánh giá của học phần.', 'D. Agrawal and Q. Zeng, Introduction to wireless and mobile systems, Cengage Learning, ISBN-10: 1-4390-6205-6, 2011.\r\nWaltenegus Dargie, Christian Poellabauer, Fundamentals of Wireless Sensor Networks: Theory and Practice, John Wiley & Sons Ltd, ISBN: 978-0-470-99765-9, 2010.', 'Pradeeka Seneviratne, Beginning LoRa Radio Networks with Arduino: Build Long Range,\r\nLow Power Wireless IoT Networks, Apress Media LLC, ISBN-13 (pbk): 978-1-4842-4356-5, 2019.\r\nPradeeka Seneviratne, Beginning LoRa Radio Networks with Arduino: Build Long Range,\r\nLow Power Wireless IoT Networks, Apress Media LLC, ISBN-13 (pbk): 978-1-4842-4356-5, 2019.', 1606262400);
INSERT INTO `table_decuongchitiet` VALUES (19, 85, 22, 0, 16, 0, 115, '74_75_150', 2, 3, 1, 4, 'Học phần này thuộc khối kiến thức chuyên ngành của các ngành: Kỹ thuật máy tính và điện tử, khoa học máy tính. Sinh viên nắm được các khái niệm cơ bản về bảo mật và an toàn hệ thống thông tin, các loại mã độc hại, các loại tấn công, các thuật mã hóa và điều khiển truy cập. Sinh viên được thực hành để phòng chống các loại mã độc, các loại tấn công trên mạng, tăng cường bảo mật mạng LAN và WLAN.', 'Hiểu được các thách thức của bảo mật thông tin và giải thích được tầm quan trọng của chúng. Sinh viên có thể nhận biết các loại tấn công cơ bản.\r\nLiệt kê và hiểu các loại mã độc hại khác nhau.\r\nMô tả các loại tấn công phi kỹ thuật.\r\nGiải thích được các loại tấn công ứng dụng web phía server và client.\r\nHiểu được các loại tấn công tầng ứng dụng.\r\nGiải thích các loại tấn công thông dụng dựa trên mạng.\r\nPhân tích các loại tấn công trên các thiết bị không dây và giải thích các cơ chế bảo mật không dây.', 'Cài đặt, cấu hình và sử dụng phần mềm diệt virus cơ bản\r\nSử dụng Microsoft’s encrypting file system (EFS).\r\nSử dụng Discretionary Access Control để chia sẻ file trên Windows', 'Giúp sinh viên hình thành thái độ học tập tích cực, đạo đức nghề nghiệp và sự tự chủ, tự chịu trách nhiệm trong giải quyết các công việc.', 'Tham gia ít nhất 80% số tiết học của lớp học phần;\r\nTham gia các hoạt động làm việc nhóm theo qui định của lớp học phần;\r\nTự tìm hiểu các vấn đề do giảng viên giao để thực hiện ngoài giờ học trên lớp;\r\nTham gia tất cả bài đánh giá của học phần.', 'C. P. (2009). Security in computing. 5th Edition. Pearson Education.', 'Cryptography and Network Security, 4th Edition, William Stallings', 1615420800);
INSERT INTO `table_decuongchitiet` VALUES (20, 112, 30, 15, 0, 90, 132, '133_188', 2, 3, 1, 4, 'Học phần lý thuyết điều khiển tự động là học phần bắt buộc, thuộc phần kiến thức chuyên ngành của chương trình đào tạo đại học ngành Công nghệ Kỹ thuật máy tính và điện tử. Học phần trang bị cho sinh viên những kiến thức cơ bản về: các thành phần của một hệ thống điều khiển tự động tuyến tính liên tục, các phương pháp xây dựng mô hình toán học của hệ thống điều khiển tự động bao gồm: hàm truyền đạt, phương trình trạng thái, các phương pháp khảo sát ổn định của hệ thống điều khiển tự động, các chỉ tiêu đánh giá chất lượng của hệ thống điều khiển và các phương pháp thiết kế hệ thống điều khiển tự động sao cho hệ ổn định và đạt được các chỉ tiêu chất lượng đề ra.', 'Mô tả, nhận diện được các phần tử cơ bản, các nguyên tắc điều khiển và các phương pháp mô tả toán học của hệ thống điều khiển tự động. Hệ thống điều khiển tự động; cấu trúc, đầu vào - đầu ra của hệ thống điều khiển; \r\nCách xây dựng hàm truyền đạt, phương trình trạng thái; \r\nCác đặc tính động học của hệ thống; \r\nCác phương pháp để khảo sát tính ổn định của hệ thống, đánh giá chất lượng hệ thống điều khiển và thiết kế hệ thống điều khiển liên tục;\r\nNguyên lý và phương pháp để đọc hiểu, áp dụng để giải quyết các bài toán về tự động; các thông số, cách thiết kế và xét tính ổn định hệ thống tự động phù hợp với yêu cầu.', 'Rèn luyện kỹ năng phân tích hệ thống, nhận diện các nguyên tắc điều khiển, các khâu động học cơ bản. Mô tả toán học các hệ thống điều khiển tự động. Trên cơ sở đó, xác định được các tiêu chuẩn xét ổn định, phân tích chất lượng hệ thống và tổng hợp thiết kế hệ thống điều khiển tự động.', 'Rèn luyện được tác phong làm việc tỉ mỉ, nghiêm túc, chủ động, tích cực, chăm chỉ, cẩn thận. Có thái độ tích cực, chủ động trong học tập, hoàn thành nhiệm vụ học tập (dự lớp, làm bài tập, trình bày kết quả, trao đổi hợp tác nhóm, lớp) và Có tính trung thực và có trách nhiệm trong quá trình làm bài tập cá nhân, làm bài tập nhóm và làm bài kiểm tra. Thực hiện các nhiệm vụ được giao đúng thời gian quy định.', 'Tham gia ít nhất 80% số tiết học của lớp học phần;\r\nTham gia các hoạt động làm việc nhóm theo qui định của lớp học phần;\r\nTự tìm hiểu các vấn đề do giảng viên giao để thực hiện ngoài giờ học trên lớp;\r\nHoàn thành tất cả bài đánh giá của học phần.', 'Nguyễn Thị Phương Hà (chủ biên) – Huỳnh Thái Hoàng, Lý thuyết điều khiển tự động, NXB Đại học Quốc gia TP HCM, Năm 2005.\r\nNguyễn Thị Phương Hà, Bài tập điều khiển tự động, NXB Đại học Quốc gia TP HCM, Năm 2005.', 'Benjamin C. Kuo, Automatic Control Systems, Prentice-Hall International Editions, Seventh Edition 1995.\r\nStanley M. Shinners, Modern Control System Theory and Design, John-Wiley and Sons 1992.\r\nNguyễn Văn Hòa, Cở sở lý thuyết điều khiển tự động, NXB KHKT, Năm 2000.\r\n] Nguyễn Thương Ngô, Lý thuyết điều khiển tự động thông thường và hiện đại (cuốn 1-4), NXB KHKT Hà Nội, Năm 2009.', 1615420800);
INSERT INTO `table_decuongchitiet` VALUES (23, 92, 20, 10, 0, 90, 148, '164_30', 2, 3, 1, 3, 'Môn học nhằm cung cấp những kiến thức tổng quát về xử lý số tín hiệu ở cấp độ cơ bản và ứng dụng cho việc giải tích xử lý tín hiệu. Những khái niệm về các hệ thống rời rạc bao gồm phương trình sai phân (vi phân), biến đổi Z, tích chập, ổn định, biến đổi Fourier rời rạc, biến đổi Fourier nhanh được giới thiệu như là những khái niệm căn bản về xử lý tín hiệu. Thiết kế mạch lọc có đáp ứng xung hữu hạn (FIR) và vô hạn (IIR) được giới thiệu như là phần ứng dụng của việc xử lý tín hiệu trong các hệ thống tuyến tính bất biến theo thời gian (LTI).', 'Hiểu được khái niệm về tín hiệu, nguyên lý xử lý tín hiệu số.\r\nMô tả được đặc tính và công dụng của phép biến đổ Z.\r\nPhân tích được tín hiệu và hệ thống trên miền tần số.', 'Vận dụng được các phương pháp phân tích và xử lý tín hiệu số.\r\nGiải quyết được các bài toán xử lý tín hiệu trong hệ thống tuyến tính bất biến theo thời gian. \r\nNâng cao khả năng lập trình xử lý tín hiệu bằng ngôn ngữ Matlab.', 'Giúp sinh viên hình thành thái độ học tập tích cực, đạo đức nghề nghiệp và sự tự chủ, tự chịu trách nhiệm trong giải quyết.', 'Tham gia ít nhất 80% số tiết học của lớp học phần;\r\nTham gia các hoạt động làm việc nhóm theo qui định của lớp học phần;\r\nTự tìm hiểu các vấn đề do giảng viên giao để thực hiện ngoài giờ học trên lớp;\r\nHoàn thành tất cả bài đánh giá của học phần.', 'Giáo trình “nhập môn xử lý tín hiệu số”, Nguyễn Lâm Đông, NXB khoa học kỹ thuật', 'S J.Orfanidis,”Introduction to Signal Processing”, Prentice –Hall Publisher 1996, ISBN 0-13-209172-0\r\nMaurice Bellanger,”Digital Processing of Signal: Theory and Practice”, John Wiley & Son Ltd 1989, ISBN 0471 921017\r\nGiáo trình “nhập môn xử lý tín hiệu số”, PGS. TS Nguyễn Quốc Trung, NXB giáo dục. \r\nBài tập “xử lý tín hiệu số” TS Hồ Văn Sung, NXB Khoa học và kỹ thuật.', 1615420800);
INSERT INTO `table_decuongchitiet` VALUES (24, 54, 30, 0, 30, 90, 50, '164_133', 2, 3, 1, 3, 'Đề cập đến các vấn đề căn bản liên quan đến vi điều khiển họ MCS-51 và kit Arduino; cấu trúc hoạt động của họ vi điều khiển MCS-51, Kit Arduino; cách thức tổ chức phần cứng, tập lệnh cùng với các hoạt động đặc trưng. Đi sâu vào thiết kế ứng dụng và một số giải thuật điều khiển, các ví dụ lập trình sử dụng ngôn ngữ lập trình C cho vi điều khiển.', 'Vẽ được sơ đồ khối, các khối chức năng, và sơ đồ mạch trong các ứng dụng cụ thể sử dụng Vi điều khiển 8051;\r\nNắm được cấu trúc kit Arduino, đặc tính và chức năng các thành phần trên kit;\r\nViết được các chương trình cơ bản, điều khiển các khối chức năng của vi điều khiển: khối vào ra, thao tác các thanh ghi, bộ định thời, ngắt, v.v cho 8051 và kit Arduino trên ngôn ngữ lập trình phần cứng như Assemnly, C.', 'Rèn luyện cho sinh viên các kỹ năng giải quyết vấn đề, tư duy, giao tiếp và tự học;\r\nThiết kế được các mạch điều khiển đơn giản;\r\nVận dụng được lý thuyết vi điều khiển vào điều khiển tự động. Xây dựng các mạch thực tế, viết chương trình phần mềm điều khiển theo yêu cầu bài toán đề ra;\r\nSử dụng thành thạo các phần mềm thiết kế, mô phỏng mạch như Protues, Keil.', 'Có ý thức tự mở rộng kiến thức môn học qua việc tìm hiểu các tài liệu về các mô đun mở rộng phần cứng;\r\nCó ý thức nâng cao khả năng kiến thức, tìm tài liệu mới về ngành nghề của mình, cập nhật thông tin;\r\nGiúp sinh viên phát triển được thái độ tốt, có ý thức chủ động, trách nhiệm và tôn trọng lẫn nhau trong học tập.', 'Tham gia ít nhất 80% số tiết học của lớp học phần;\r\nTự tìm hiểu và thực hiện các yêu cầu do giảng viên giao;\r\nHoàn thành tất cả bài đánh giá của học phần.', 'I. Scott Mackenzie, Raphael C, -W, The 8051 Microcontroller, Prentice Hall, Fourth edition.\r\nJames A. Langbridge, Arduino sketches – Tools and techniques for programming , Wiley', 'Tống Văn On, Hoàng Đức Hải, “Họ vi điều khiển 8051”, 2001.\r\nNguyễn Tăng Cường, “Cấu trúc và lập trình họ VĐK 8051”, 2003', 1615420800);
INSERT INTO `table_decuongchitiet` VALUES (25, 91, 23, 0, 15, 0, 134, '83_133', 1, 1, 1, 4, 'Học phần nhằm cung cấp cho sinh viên kiến thức cơ bản về xử lý ảnh, giúp sinh viên rèn luyện và sử dụng thành thạo các thư viện và công cụ trong xử lý ảnh (OpenCV, Python/C++).  Dựa trên kiến thức và kỹ năng được cung cấp, sinh viên có thể tự phát triển các ứng dụng cơ bản liên quan đến xử lý ảnh như: biểu diễn ảnh trong máy tính, các phép biến đổi ảnh, các bộ lọc ảnh, nâng cấp và phân đoạn ảnh, trích xuất đặc trưng ảnh,...', 'Hiểu được các khái niệm cơ bản, các mô hình toán học và phương pháp trong xử lý ảnh.\r\nHiểu được chức năng các thư viện OpenCV, ngôn ngữ lập trình (Python/C++)  hỗ trợ để hiện thực các thuật toán trong xử lý ảnh.\r\nPhát triển và áp dụng các kỹ thuật xử lý ảnh để giải quyết các vấn đề thực tế.', 'Phát triển được các kỹ năng làm việc nhóm, kỹ năng giao tiếp, kỹ năng tư duy và giải quyết vấn đề\r\nKỹ năng sử dụng thư viện và ngôn ngữ lập trình (OpenCV, Python/C++) để cài đặt các chương trình xử lý ảnh trên máy tính.', 'Phát triển được tính chuyên nghiệp trong môi trường công việc. Có tinh thần hợp tác, hỗ trợ, chia sẻ và tôn trọng lẫn nhau.', 'Tham gia ít nhất 80% số tiết học của lớp học phần\r\nTham gia các hoạt động làm việc nhóm theo qui định của lớp học phần\r\nTự tìm hiểu các vấn đề do giảng viên giao để thực hiện ngoài giờ học trên lớp\r\nTự tìm hiểu các vấn đề do giảng viên giao để thực hiện ngoài giờ học trên lớp', 'Digital Image Processing, 4  Edition,  Rafael C. Gonzalez and Richard E. Woods, Pearson Education, 2018.', 'Image Processing and Acquisition using Python, Chandrajit Bajaj and Guillermo Sapiro, CRC Press, Taylor & Francis Group, 2013\r\nSlides bài giảng', 1618876800);
INSERT INTO `table_decuongchitiet` VALUES (26, 114, 30, 0, 30, 90, 85, '', 1, 1, 1, 3, 'Môn học này trang bị cho sinh viên các kiến thức cơ bản về hệ cơ sở dữ liệu phân tán, kiến trúc và ứng dụng vào thực tế đối với các doanh nghiệp lớn hiện nay. Nội dung cụ thể cung cấp: các phương pháp phân mảnh dữ liệu và điều kiện kiểm tra tính đúng đắn trong phân mảnh; Tiếp cận cách thiết kế hệ CSDL phân tán và ứng dụng các thuật toán trong thiết kế; Biến đổi truy vấn toàn cục thành truy vấn phân mảnh và tối ưu hóa truy vấn dữ liệu phân tán; Các nguyên lý quản lý giao dịch, kiểm soát dữ liệu ngữ nghĩa và điều khiển đồng thời trong phân tán. Ngoài ra, cung cấp các bài tập phân mảnh dữ liệu, phân tích, thiết kế ứng dụng cơ sở dữ liệu phân tán và cài đặt trên hệ quản lý cơ sở dữ liệu phân tán như: SQL Server, Oracle, DB2, PostgresSQL. Cuối cùng, một đồ án môn học làm việc theo nhóm từ 2-3 sinh viên thực hiện dựa trên nghiệp vụ thực tế', 'Nắm được các khái niệm cơ bản về hệ cơ sở dữ liệu phân tán; so sánh được những ưu và hạn chế giữa cơ sở dữ liệu tập trung và cơ sở dữ liệu phân tán.\r\nCó kiến về các hướng thức tiếp cận và thiết kế một hệ cơ sở dữ liệu phân tán: các phương pháp phân mãnh dữ liệu, nhân bản, điều khiển đồng thời; quản lý giao tác, kiểm soát dữ liệu ngữ nghĩa và truy vấn phân tán\r\nCó kiến thức về ứng dụng của hệ CSDL phân tán trong quản lý các tổ chức doanh nghiệp', 'Truy vấn và cập nhật đồng bộ dữ liệu trên các database server\r\nBiết tối ưu hóa truy vấn phân tán\r\nCài đặt được cơ sở dữ liệu phân tán cho bài toán trên một hệ quản trị CSDL(SQL Server, DB2 IBM, Oracle…)\r\nCó kỹ năng làm việc nhóm, kỹ năng thuyết trình một đề tài.', 'Giúp sinh viên hình thành thái độ học tập tích cực, đạo đức nghề nghiệp và sự tự chủ, tự chịu trách nhiệm trong giải quyết các công việc.\r\nTôn trọng quyền tác giả, sử dụng phần mềm hợp pháp\r\nChuẩn bị bài trước khi đến lớp. Đi học đầy đủ. Tham gia tích cực trong giờ học.\r\nLàm tất cả các bài tập lý thuyết và thực hành. Tham gia tích cực vào nhóm làm đồ án môn học.', 'Tham gia ít nhất 80% số tiết học của lớp học phần;\r\nTự nghiên cứu các vấn đề do giảng viên giao ở nhà hoặc thư viện;\r\nTự tìm hiểu các vấn đề do giảng viên giao để thực hiện ngoài giờ học trên lớp;\r\nTham gia tất cả các bài đánh giá của học phần.', 'Principples of Distributed Database Systems, M.Tamer Ozsu and Patrick Valduries, New York Dordrecht Heidelberg London: Springer, 2020.', 'Principples of Distributed Database Systems, M.Tamer Ozsu and Patrick Valduries, New York Dordrecht Heidelberg London: Springer, 2020.', 1619049600);
INSERT INTO `table_decuongchitiet` VALUES (27, 46, 30, 0, 0, 60, 28, '137_136', 1, 1, 1, 3, 'Nhập môn Công Nghệ Phần Mềm là môn học nhằm giúp cho sinh viên có kiến thức cơ bản nhất trong lĩnh vực công nghệ phần mềm. Qua môn học này sinh viên có cái nhìn khái quát về qui trình phát triển phần mềm, hiểu biết và thực hiện các giai đoạn trong qui trình trên một phần mềm cụ thể dựa trên những phương pháp, kỹ thuật trong quá trình thu thập yêu cầu, phân tích, thiết kế và cài đặt, viết sưu liệu đã được minh họa cụ thể trong giáo trình.', 'Trang bị cho sinh viên các kiến thức cơ bản về công nghệ phần mềm.\r\nCung cấp kiến thức nền tảng trong về các quy trình phát triển phần mềm.\r\nCác kỹ thuật công cụ đặc tả, phân tích, thiết kế phần mềm,...', 'Giúp sinh viên nắm được kiến thức về qui trình phát triển phần mềm, các kỹ thuật quản lý, phát triển dự án….', 'Giúp sinh viên hình thành thái độ học tập tích cực, đạo đức nghề nghiệp và sự tự chủ, tự chịu trách nhiệm trong giải quyết các vấn đề liên quan đến công nghệ phần mềm', 'Dự lớp không thấp hơn 80% số tiết lên lớp qui định của học phần;\r\nLàm và nộp các bài tập cá nhân/ nhóm theo qui định của học phần;\r\nTự nghiên cứu các vấn đề do giảng viên giao ở nhà hoặc thư viện;\r\nThảo luận nhóm theo chủ đề;\r\nThực hiện bài tập theo nhóm;\r\nTham dự kiểm tra giữa kỳ và thi kết thúc học phần.', 'Ian Sommerville, Software Engineering, 7th edition, Pearson Education, 2004.', 'Stephen R. Schach, Classical and Object-Oriented Software Engineering, NXB IRWIN, 1996.\r\nRonald Leach, Introduction to Software Engineering, CRC Press, 1999.\r\nG. Booch, J. Rumbaugh, I. Jacobson, The Unified Modeling Language User Guide, Addision-Wesley, 1999.\r\nCraig Larman, Applying UML and Patterns: An Introduction to Object-Oriented Analysis and Design and Iterative Development, Third Edition, Addision-Wesley, 2004.\r\nGlenford J. Myers, The art of software testing, Wiley, 2004.\r\nBoris Beizer, Software Testing Techniques, Second Edition.', 1619049600);
INSERT INTO `table_decuongchitiet` VALUES (28, 47, 30, 0, 0, 90, 84, '222', 1, 1, 1, 4, 'Học phần nhằm cung cấp cho sinh viên kiến thức cơ bản về ngôn ngữ lập trình Ruby,  và web framework mã nguồn mỡ Ruby On Rails. Học phần giúp sinh viên có thể ứng dụng ngôn ngữ lập trình hướng đối tượng Ruby để xây dựng, phát triển các ứng dụng, đặc biệt là các ứng dụng web, dựa trên Ruby On Rails. Chuyên đề Ruby On Rails thuộc khối kiến thức chuyên ngành của ngành CNTT và được giảng dạy cho các sinh viên thuộc ngành CNTT.', 'Trang bị cho sinh viên những kiến thức nền tảng và những ký năng cần thiết để có thể lập trình với ngôn ngữ lập trình hướng đối tượng Ruby trên nền tảng Ruby On Rails. Trên cơ sở đó, giúp sinh viên có thể sử dụng các cấu trúc và cú pháp của ngôn ngữ lập trình Ruby để xây dựng và phát triển các ứng dụng.', 'Rèn luyện cho sinh viên (lập luận phân tích và giải quyết vấn đề, tư duy hệ thống) và kỹ năng giao tiếp (làm việc nhóm, ngoại ngữ) để tìm hiểu tài liệu và thực hiện phát triển phần mềm bằng ngôn ngữ lập trình Ruby; cùng với kỹ năng nghề nghiệp trong môi trường doanh nghiệp và xã hội trong quá trình phân tích và phát triển ứng dụng phần mềm.', 'Giúp sinh viên hình thành thái độ học tập tích cực, đạo đức nghề nghiệp và sự tự chủ, tự chịu trách nhiệm trong giải quyết....', 'Tham gia ít nhất 80% số tiết học của lớp học phần;\r\nTham gia các hoạt động làm việc nhóm theo qui định của lớp học phần;\r\nTự tìm hiểu các vấn đề do giảng viên giao để thực hiện ngoài giờ học trên lớp;\r\nHoàn thành tất cả bài đánh giá của học phần.', 'Michael Hartl, Ruby On Rails Tutorial, Sixth Edition.', 'Sam Ruby, Dave Thomas, David Heinemeier Hanson Agile Web Development with Rails 5, 2017.', 1619049600);
INSERT INTO `table_decuongchitiet` VALUES (29, 88, 22, 15, 0, 90, NULL, '66_27_170_10', 1, 1, 1, 4, 'Học phần nhằm cung cấp cho sinh viên kiến thức cơ bản về kiểm thử và các hoạt động kiểm thử phần mềm. Học phần giúp sinh viên có thể áp dụng các kỹ thuật kiểm thử và các công cụ kiểm thử phần mềm cho các bài toán thực tế. Học phần Kiểm thử phần mềm thuộc khối kiến thức cơ sở ngành của ngành CNTT và được giảng dạy sau khi sinh viên đã học về Công nghệ phần mềm', 'Trang bị cho sinh viên những kiến thức niệm cơ bản liên quan đến kiểm thử phần mềm: khái niệm kiểm thử, các kỹ thuật kiểm thử phần mềm, công cụ kiểm thử và khả năng áp dụng kiến thức vào hoạt động kiểm thử phần mềm một cách có hệ thống và có phương pháp. Trong đó có sử dụng một số công cụ hỗ trợ cho quá trình phân tích, thiết kế, thực hiện và báo cáo kết quả kiểm thử phần mềm.', 'Rèn luyện cho sinh viên (lập luận phân tích và giải quyết vấn đề, tư duy hệ thống) và kỹ năng giao tiếp (làm việc nhóm, ngoại ngữ) để tìm hiểu tài liệu và thực hiện đồ án; cùng với kỹ năng nghề nghiệp trong môi trường doanh nghiệp và xã hội trong quá trình phân tích, thiết kế, cài đặt và kiểm thử hệ thống', 'Giúp sinh viên hình thành thái độ học tập tích cực, đạo đức nghề nghiệp và sự tự chủ, tự chịu trách nhiệm trong giải quyết....', 'Tham gia ít nhất 80% số tiết học của lớp học phần;\r\nTham gia các hoạt động làm việc nhóm theo qui định của lớp học phần;\r\nTự tìm hiểu các vấn đề do giảng viên giao để thực hiện ngoài giờ học trên lớp;\r\nHoàn thành tất cả bài đánh giá của học phần.', 'Dorothy Graham, Erik van VeenenDaal, Isabel Evans, Rex Black, Foundations of Software Testing, ISTQB Certification, Thomson.', 'Nguyễn Thanh Bình, Kiểm thử phần mềm, NXB Giáo dục, 2013.\r\nAndreas Spillner, Tilo Linz, Hans Schaefer, Software Testing Foundations, Rocky Nook, 2014.\r\nPaul Ammann, Jeff Offutt, Introduction to Software Testing, Cambridge University Press, 2017', 1619308800);
INSERT INTO `table_decuongchitiet` VALUES (30, 51, 60, 0, 30, 120, 178, '137_23_173', 1, 1, 1, 3, 'Cung cấp cho sinh viên kiến thức về lập trình cho các thiết bị chạy hệ điều hành Android. Kết thúc môn học, sinh viên có thể thiết kế và phát triển các ứng dụng di động trên hệ điều hành Android. Phát triển cho sinh viên khả năng thiết kế, lập trình và triển khai các ứng dụng di động hiện tại và các ứng dụng di động mới sau này.', 'Hiểu các khái niệm cơ bản của lập trình Android. Kiến trúc Android, vòng đời của một ứng dụng Android\r\nXây dựng giao diện cho một ứng dụng Android với các thành phần cơ bản\r\nLập trình với cơ sở dữ liệu SQLite, web service\r\nLập trình với Service, Notification, Activity State and Preferences, Maps and GPS, Using the Camera.', 'Áp dụng kiến thức đã học để viết một ứng dụng Android\r\nPhát triển kỹ năng tự học, giao tiếp, làm việc nhóm', 'Giúp sinh viên hình thành thái độ học tập tích cực, đạo đức nghề nghiệp và sự tự chủ, tự chịu trách nhiệm trong giải quyết các vấn đề liên quan đến công nghệ di động.', 'Dự lớp không thấp hơn 80% số tiết lên lớp qui định của học phần;\r\nLàm và nộp các bài tập cá nhân/ nhóm theo qui định của học phần;\r\nTự nghiên cứu các vấn đề do giảng viên giao ở nhà hoặc thư viện;', NULL, 'Google, (2018), “Android Developer Fundamentals v2-2018”', 1619308800);
INSERT INTO `table_decuongchitiet` VALUES (31, 52, 30, 0, 0, 0, 18, '64_150_1_174', 1, 1, 1, 3, 'Học phần tiếng anh chuyên ngành bao gồm các bài đọc liên quan về lĩnh vực công nghệ thông tin phù hợp với giai đoạn đầu học chuyên ngành của sinh viên công nghệ thông tin và hướng dẫn thực tập cách thực hiện bài báo cáo tiếng Anh trên powerpoint, khả năng đọc bài báo tiếng anh chuyên ngành, làm báo cáo dự án bằng tiếng anh.', 'Nắm bắt được các các từ vựng chuyên ngành công nghệ thông tin\r\nÁp dụng kiến thức về ngữ pháp, từ vựng và sử dụng công cụ từ điển để đọc tài liệu tiếng Anh\r\nÁp dụng ngữ pháp và từ vựng để viết các ý tưởng liên quan đến công nghệ bằng tiếng Anh', 'Vận dụng tất cả kiến thức đã học để làm báo cáo một dự án công nghệ thông tin bằng tiếng Anh \r\nVận dụng kỹ năng tự luyện tập để nghe và trả lời các câu hỏi bằng tiếng Anh', 'Giúp sinh viên hình thành thái độ học tập tích cực, đạo đức nghề nghiệp và sự tự chủ, tự chịu trách nhiệm trong giải quyết....', 'Tham gia ít nhất 80% số tiết học của lớp học phần;\r\nTham gia các hoạt động làm việc nhóm theo qui định của lớp học phần;\r\nTự tìm hiểu các vấn đề do giảng viên giao để thực hiện ngoài giờ học trên lớp;\r\nHoàn thành tất cả bài đánh giá của học phần.', 'Tiếng Anh: Oxford English for Computing, Keith Boeckner – P.Charles Brown,', 'Oxford English for Information Technology, Eric H. Glendining, John McEwan\r\nComputer Science, Trica Walker.', 1619308800);
INSERT INTO `table_decuongchitiet` VALUES (32, 15, 30, 0, 30, 60, 9, '66_169', 1, 1, 1, 4, 'Học phần nhằm cung cấp cho sinh viên kiến thức cơ bản về các cấu trúc dữ liệu, như danh sách, ngăn xếp, hàng đợi, cây, đồ thị... Ngoài ra, học phần cung cấp một số giải thuật, như: Đệ quy, sắp xếp... và các giải thuật xử lý trên các cấu trúc dữ liệu. Học phần giúp sinh viên có thể áp dụng giải quyết các bài toán tin học trong thực tế.  Học phần Cấu trúc dữ liệu và giải thuật thuộc khối kiến thức cơ sở của ngành CNTT.', 'Trang bị cho sinh viên những khái niệm cơ bản liên quan đến cấu trúc dữ liệu và giải thuật, khả năng thiết kế các cấu trúc dữ liệu và giải thuật để giải quyết các bài toán tin học.', 'Rèn luyện cho sinh viên các kỹ năng tư duy, kỹ năng giao tiếp và kỹ năng giải quyết vấn đề.', 'Giúp sinh viên phát triển được tính chuyên nghiệp trong môi trường công việc và trong phát triển phần mềm, có ý thức chủ động, sáng tạo và trách nhiệm trong các hoạt động nghề nghiệp', 'Tham gia ít nhất 80% số tiết học của lớp học phần;\r\nTham gia các hoạt động làm việc nhóm theo qui định của giảng viên;\r\nTự tìm hiểu các vấn đề do giảng viên giao để thực hiện ngoài giờ học trên lớp;\r\nHoàn thành tất cả bài đánh giá của học phần.', 'Reema Thareja, Data Structures Using C - Second Edition, Oxford University Press, 2014.', 'Đỗ Xuân Lôi, Cấu trúc dữ liệu và giải thuật, In lần thứ 9, NXB Đại học quốc gia Hà Nội, 2006.\r\nTrần Hạnh Nhi, Dương Anh Đức, Giáo trình Cấu trúc dữ liệu và giải thuật, NXB Đại học quốc gia TPHCM, 2010.\r\nMark Allen Weiss, Data Structures and Algorithm Analysis in C++, 4th Edition, Pearson Education, 2014', 1619308800);
INSERT INTO `table_decuongchitiet` VALUES (33, 16, 30, 30, 30, 120, 28, '172_20_18', 1, 1, 1, 3, 'Môn học ”Công nghệ Web” giới thiệu cho người học những kiến thức cơ bản về Internet, cách tạo một Website đơn giản, cung cấp kiến thức nền tảng trong việc thiết kế Website tĩnh với công nghệ HTML5, CSS3, Javascript tạo tiền đề cho việc phát triển và lập trình Web động.', 'Hiểu được nguyên tắc thiết kế được một website tĩnh cho cá nhân hay tổ chức và biết cách quản lý và xuất bản website lên internet, mục đích của website cần thiết kế và chiến lược thiết kế.\r\nThành thạo với ngôn ngữ HTML, định dạng trang Web dùng CSS, lập trình javascript để tạo các trang web.\r\nPhát triển với công nghệ HTML5 và CSS3, triển khai website với jQuery công nghệ mới, thiết kế web cơ bản máy tính và trên di động.', 'Giúp sinh viên thiết kế được một Website tĩnh, và biết tìm kiếm, sử dụng những công cụ có sẵn hỗ trợ cho việc thiết kế Website, biết cách quản lý và xuất bản Website lên Internet', 'Sinh viên có thái độ, động cơ học tập rõ ràng, chú ý nghe giảng trên lớp tích cực nghiên cứu tài liệu, làm thực hành ở nhà và tham gia thảo luận nhóm.\r\nXác định phương pháp học tập hiệu quả và có khoa học, có tinh thần và ý thức học tập cao.\r\nSinh viên đam mê và thích thú với thiết kế, kết quả là ứng dụng website thực tế.', 'Tham gia ít nhất 80% số tiết học của lớp học phần;\r\nTham gia các hoạt động làm việc nhóm theo quy định của lớp học phần;\r\nTự tìm hiểu các vấn đề do giảng viên giao để thực hiện ngoài giờ học trên lớp;\r\nHoàn thành tất cả bài đánh giá của học phần.', 'Aptech Computer Education, HTML5 - NextGen Web – International, 2013.\r\nDan Cederholm, CSS3 For Web Designers. Nhà xuất bản Happy Cog. Số trang 120.\r\nJeremy Osborn và AGI Creative Team, 2012, Adobe Dreamweaver CS6 Digital Classroom. Nhà xuất bản Wiley. Số trang 496.\r\nJoe Fawcett, Danny Ayers, Liam R. E. Quin, 2012, Beginning XML. Nhà xuất bản Wrox. Số trang 864.', 'NEU - EDUTOP, 2006, Tổng quan về Internet\r\nSteve Suehring, 2013, JavaScript Step by Step. Nhà xuất bản Microsoft Press. Số trang 482.\r\nW3schools, 2003, HTML. http://w3schools.com/html/\r\nWallpearl, 2008, Simple CSS. Nhà xuất bản WallPerl. Số trang 65.', 1619308800);
INSERT INTO `table_decuongchitiet` VALUES (34, 20, 22, 30, 18, 60, 8, '1_10_156', 1, 1, 1, 3, 'Học phần Java nâng cao bao gồm kiến thức lập trình ngôn ngữ Java ở mức độ nâng cao phù hợp với giai đoạn đầu học chuyên ngành của sinh viên công nghệ thông tin và hướng dẫn thực tập cách xây dựng chương trình máy tính, khả năng đọc mã nguồn của chương trình khác, …', 'Nắm bắt được các đặc điểm của ngôn ngữ lập trình Java\r\nNắm bắt được cách xây dựng, lập trình và sữa lỗi một chương trình Java\r\nÁp dụng kiến thức để đọc và hiểu mã nguồn của một chương trình có sẵn', 'Nắm bắt được các đặc điểm của ngôn ngữ lập trình Java\r\nNắm bắt được cách xây dựng, lập trình và sữa lỗi một chương trình Java\r\nÁp dụng kiến thức để đọc và hiểu mã nguồn của một chương trình có sẵn', 'Chuẩn hóa kỹ thuật, sinh viên thông qua nắm các kỹ thuật cơ bản để tự tiếp cận xây dựng các ứng dụng web/mạng/desktop thực tế, giải quyết bài toán thực tế', 'Tham gia ít nhất 80% số tiết học của lớp học phần;\r\nTham gia đầy đủ các bài tập theo qui định của lớp học phần;\r\nTự tìm hiểu các vấn đề do giảng viên giao để thực hiện ngoài giờ học trên lớp;\r\nHoàn thành tất cả bài đánh giá của học phần.', 'Tài liệu slide do giảng viên Trường Đại học Công nghệ Thông tin và Truyền thông Việt - Hàn soạn giảng.\r\nBài tập Lập Trình Java- Huỳnh Công Pháp\r\nEckel, B., 2013. Thinking in JAVA. Prentice Hall Professional.\r\nRedko, A., 2017. Advance JAVA. Java Code Geek.', 'Core Java I và Core Java II: phiên bản in lần thứ 10\r\nJava Murach\r\nHorstmann, C.S. and Cornell, G., 2002. Core Java 2: Volume I, Fundamentals. Pearson Education.\r\nDeitel, H.M., Deitel, P.J. and Santry, S.E., 2001. Advanced Java 2 platform How to program. Prentice Hall PTR.', 1619308800);

SET FOREIGN_KEY_CHECKS = 1;
