/*
 Navicat Premium Data Transfer

 Source Server         : Mysql_DB
 Source Server Type    : MySQL
 Source Server Version : 100417
 Source Host           : localhost:3306
 Source Schema         : demovku

 Target Server Type    : MySQL
 Target Server Version : 100417
 File Encoding         : 65001

 Date: 13/05/2021 15:49:27
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for table_hocphan_noidung
-- ----------------------------
DROP TABLE IF EXISTS `table_hocphan_noidung`;
CREATE TABLE `table_hocphan_noidung`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_hocphan` int NULL DEFAULT NULL,
  `id_lhp` varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `buoi` int NULL DEFAULT NULL,
  `noidung_chuong` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `trangthai` int NULL DEFAULT 1,
  `created_at` datetime(0) NULL DEFAULT NULL,
  `updated_at` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 686 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of table_hocphan_noidung
-- ----------------------------
INSERT INTO `table_hocphan_noidung` VALUES (17, 68, NULL, 1, 'Chương 1. Khái niệm\r\nchung\r\n1.1. Kiến trúc mạng\r\n1.2. Lập trình mạng\r\n1.3. Các loại mạng\r\n1.4. Hệ điều hành\r\n1.5. Tập giao thức', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (18, 68, NULL, 2, 'Chương 2. Các mô hình\r\nmạng\r\n2.1. Mô hình truyền thông\r\ntrong kiến trúc mạng\r\n2.2. Các giao thức\r\n2.3. Mô hình TCP/IP', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (19, 68, NULL, 3, 'Chương 3. Các mô hình\r\nứng dụng mạng\r\n3.1. Mô hình client server\r\n3.2. Mô hình ứng dụng\r\nP2P\r\n3.3. Mô hình phân tán', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (20, 68, NULL, 4, 'Chương 4. Lập trình với\r\ngiao thức TCP\r\n4.1. Giao thức TCP/IP\r\n4.2. Lập trình Socket', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (21, 68, NULL, 5, 'Kiểm tra giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (22, 68, NULL, 6, 'Chương 5. Lập trình với\r\ngiao thức UDP', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (23, 68, NULL, 7, 'Chương 6. Lập trình\r\nmulticast', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (24, 68, NULL, 8, 'Chương 7. Giao thức\r\nHTTP\r\n7.1. Tổng quan\r\n7.2. Cơ chế hoạt động\r\n7.3. Web Server', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (25, 68, NULL, 9, 'Chương 8. Gọi hàm và thủ\r\ntục từ xa\r\n8.1. Lập trình RPC\r\n8.2. Lập trình RMI\r\n8.3. Lập trình CORBA', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (26, 68, NULL, 10, 'Chương 9. Kiến trúc\r\nhướng dịch vụ SOA', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (27, 12, NULL, 1, 'UNIT 6: OUT AND ABOUT. 6.1. Vocabulary and Listening: In Town', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (28, 12, NULL, 2, '6.2. Grammar: Past Simple – BE and CAN. 6.3. Culture: Tourist information', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (29, 12, NULL, 3, '6.4. Grammar: Past Simple:Negative and Interrogative. 6.5. Reading: Out on the Town', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (30, 12, NULL, 4, '6.6. Everyday English: On the Phone', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (31, 12, NULL, 5, '6.7. Writing: A Message', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (32, 12, NULL, 6, 'UNIT 7: WORLD FAMOUS. 7.1. Vocabulary and Listening: On the Map. 7.2. Grammar: Past Simple (Irregular Verbs)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (33, 12, NULL, 7, '7.3. Culture: An American Hero', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (34, 12, NULL, 8, '7.4. Grammar: Past Simple - Negative and Interrogative. 7.5. Reading: Inventions', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (35, 12, NULL, 9, '7.6. Everyday English: Talking about Your Weekend', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (36, 12, NULL, 10, '7.7. Writing: An E-mail Message. Kiểm tra giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (37, 12, NULL, 11, 'Unit 8: ON THE MENU. 8.1. Vocabulary and Listening: Breakfast. 8.2. Grammar: Some and Any, How Much and How Many', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (38, 12, NULL, 12, '8.3. Culture: Traditional Dishes', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (39, 12, NULL, 13, '8.4. Grammar: Articles. 8.5. Reading: Healthy Eating', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (40, 12, NULL, 14, '8.6. Everyday English: In a Cafe', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (41, 12, NULL, 15, '8.7. Writing: A Formal Letter. Revision', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (42, 22, NULL, 1, 'UNIT 9: JOURNEYS. 9.1. Vocabulary and listening: Transport', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (43, 22, NULL, 2, '9.2. Grammar: Present perfect: Affirmative', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (44, 22, NULL, 3, '9.3.Culture: People on the move', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (45, 22, NULL, 4, '9.4. Grammar: Present perfect: negative and interrogative', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (46, 22, NULL, 5, '9.5. Reading: Alone on the water. 9.6. Everyday English: Buying a train ticket', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (47, 22, NULL, 6, '9.7. Writing: An e-mail. * Practice test', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (48, 22, NULL, 7, 'Kiểm tra giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (49, 22, NULL, 8, 'Unit 10: JUST THE JOB 10.1.Vocabulary and listening: Jobs and work', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (50, 22, NULL, 9, '10.2.Gramm ar: going to', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (51, 22, NULL, 10, '10.3. Culture: Jobs for teenagers', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (52, 22, NULL, 11, '10.4. Grammar: Will', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (53, 22, NULL, 12, '10.5. Reading : A year abroad', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (54, 22, NULL, 13, '10.6. Everyday English: Giving advice', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (55, 22, NULL, 14, '10.7. Writing: An application letter.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (56, 22, NULL, 15, 'Revision', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (58, 37, NULL, 1, 'UNIT 1. THE REAL YOU', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (59, 37, NULL, 2, '1.1.Vocabulary and Listening: Personalities', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (60, 37, NULL, 3, '1.2.Grammar: Present simple and continuous', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (61, 37, NULL, 4, '1.3.Culture: Free time', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (62, 37, NULL, 5, '1.4. Grammar: Verb patterns', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (63, 37, NULL, 6, '1.5. Reading: Appearances', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (64, 37, NULL, 7, '1.6. Everyday English: Giving opinions', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (65, 37, NULL, 8, 'Kiểm tra giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (66, 37, NULL, 9, '1.7. Writing: A personal profile * Practice test', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (67, 37, NULL, 10, 'UNIT 2: WINNING AND LOSING. 2.1. Vocabulary and Listening: A question of Sports', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (68, 37, NULL, 11, '2.2. Grammar: Past simple. 2.3. Culture: On the river', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (69, 37, NULL, 12, '2.4. Grammar: Past Continuous. 2.5.Reading: Surf’s up', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (70, 37, NULL, 13, '2.6.Everyday English: Talking about the past', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (71, 37, NULL, 14, '2.7. Writing: A magazine article', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (72, 37, NULL, 15, 'Revision', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (73, 81, NULL, 1, 'CHƯƠNG 1: TRIẾT HỌC VÀ VAI TRÒ CỦA TRIẾT HỌC TRONG ĐỜI SỐNG XÃ HỘI', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (74, 81, NULL, 2, '1.1. Triết học và vấn đề cơ bản của triết học. 1.2. Triết học Mác - Lênin và vai trò của triết học Mác – Lênin trong đời sống xã hội', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (76, 81, NULL, 3, 'Vai trò của triết học Mác - Lênin trong đời sống xã hội và trong sự nghiệp đổi mới ở Việt Nam hiện nay', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (77, 81, NULL, 4, 'CHƯƠNG 2: CHỦ NGHĨA DUY VẬT BIỆN CHỨNG. 2.1. Vật chất và ý thức', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (80, 81, NULL, 5, '2.1. Vật chất và ý thức (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (81, 81, NULL, 6, '2.2. Phép biện chứng duy vật', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (83, 81, NULL, 7, 'Nội dung của phép biện chứng duy vật', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (85, 81, NULL, 8, '2.3. Lý luận nhận thức ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (88, 81, NULL, 9, 'Bài KT giữa kỳ ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (89, 81, NULL, 10, 'CHƯƠNG 3: CHỦ NGHĨA DUY VẬT LỊCH SỬ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (90, 81, NULL, 11, '3.1. Học thuyết hình thái kinh tế - xã hội', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (93, 81, NULL, 12, '3.2. Giai cấp và dân tộc', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (95, 81, NULL, 13, '3.3. Nhà nước và cách mạng xã hội', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (97, 81, NULL, 14, '3.4. Ý thức xã hội', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (99, 81, NULL, 15, '3.5. Triết học về con người', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (102, 106, NULL, 1, 'CHƯƠNG 1. NHẬP MÔN CHỦ NGHĨA XÃ HỘI KHOA HỌC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (104, 106, NULL, 2, 'CHƯƠNG 2. SỨ MỆNH LỊCH SỬ CỦA GIAI CẤP CÔNG NHÂN. 2.1. Quan điểm cơ bản của chủ nghĩa Mác - Lênin về giai cấp công nhân và sứ mệnh lịch sử thế giới của giai cấp công nhân', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (106, 106, NULL, 3, '2.2. Giai cấp công nhân và thực hiện sứ mệnh lịch sử của giai cấp công nhân hiện nay. 2.3. Sứ mệnh lịch sử của giai cấp công nhân Việt Nam', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (108, 106, NULL, 4, 'CHƯƠNG 3. CHỦ NGHĨA XÃ HỘI VÀ THỜI KỲ QUÁ ĐỘ LÊN CHỦ NGHĨA XÃ HỘI. 3.1. Chủ nghĩa xã hội', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (110, 106, NULL, 5, '3.2. Thời kỳ quá độ lên chủ nghĩa xã hội', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (113, 106, NULL, 6, '3.3. Quá độ lên chủ nghĩa xã hội ở Việt Nam', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (115, 106, NULL, 7, 'CHƯƠNG 4. DÂN CHỦ XÃ HỘI CHỦ NGHĨA VÀ NHÀ NƯỚC XÃ HỘI CHỦ NGHĨA. 4.1. Dân chủ và dân chủ xã hội chủ nghĩa. 4.2. Nhà nước xã hội chủ nghĩa', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (117, 106, NULL, 8, '4.3. Dân chủ xã hội chủ nghĩa và xây dựng nhà nước pháp quyền xã hội chủ nghĩa ở Việt Nam ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (119, 106, NULL, 9, 'CHƯƠNG 5. CƠ CẤU XÃ HỘI – GIAI CẤP VÀ LIÊN MINH GIAI CẤP, TẦNG LỚP TRONG THỜI KỲ QUÁ ĐỘ LÊN CHỦ NGHĨA XÃ HỘI. 5.1. Cơ cấu xã hội - giai cấp trong thời kỳ quá độ lên chủ nghĩa xã hội', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (121, 106, NULL, 10, '5.2. Liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên chủ nghĩa xã hội', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (123, 106, NULL, 11, '5.3. Cơ cấu xã hội - giai cấp và liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên chủ nghĩa xã hội ở Việt Nam', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (125, 106, NULL, 12, 'CHƯƠNG 6. VẤN ĐỀ DÂN TỘC VÀ TÔN GIÁO TRONG THỜI KỲ QUÁ ĐỘ LÊN CHỦ NGHĨA XÃ HỘI. 6.1. Dân tộc trong thời kỳ quá độ lên chủ nghĩa xã hội', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (127, 106, NULL, 13, '6.2. Tôn giáo trong thời kỳ quá độ lên CNXH ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (130, 106, NULL, 14, '6.3. Quan hệ giữa dân tộc và tôn giáo ở Việt Nam. CHƯƠNG 7.  VẤN ĐỀ GIA ĐÌNH TRONG THỜI KỲ QUÁ ĐỘ LÊN CHỦ NGHĨA XÃ HỘI. 7.1. Khái niệm, vị trí và chức năng của gia đình', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (132, 106, NULL, 15, '7.2. Cơ sở xây dựng gia đình trong thời kỳ quá độ lên chủ nghĩa xã hội. 7.3. Xây dựng gia đình Việt Nam trong thời kỳ quá độ lên chủ nghĩa xã hội', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (133, 105, NULL, 1, 'CHƯƠNG 1: ĐỔI TƯỢNG, PHƯƠNG PHÁP NGHIÊN CỨU VÀ CHỨC NĂNG CỦA KINH TỂ CHÍNH TRỊ MÁC – LÊNIN. ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (134, 105, NULL, 2, 'CHƯƠNG 2: HÀNG HÓA, THỊ TRƯỜNG VÀ VAI TRÒ CỦA CÁC CHỦ THỂTHAM GIA THỊ TRƯỜNG. 2.1. Lý luận của C. Mác về sản xuất hàng hóa và hàng hóa', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (135, 105, NULL, 3, '2.2. Thị trường và vai trò của các chủ thể tham gia thị trường', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (136, 105, NULL, 4, '2.3. Vai trò của một số chủ thể tham gia thị trường. CHƯƠNG 3: GIÁ TRỊ THẶNG DƯ TRONG NỀN KINH TẾ THỊ TRƯỜNG. 3.1. Lý luận của C.Mác về giá trị thặng dư.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (137, 105, NULL, 5, '3.2. Tích lũy tư bản', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (138, 105, NULL, 6, '3.3. Các hình thức biểu hiện của giá trị thặng dư trong nền kinh tế thị trường', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (139, 105, NULL, 7, 'CHƯƠNG 4: CẠNH TRANH VÀ ĐỘC QUYỀNTRONG NỀN KINH TẾ THỊ TRƯỜNG. 4.1. Cạnh tranh ở cấp độ độc quyền trong nền kinh tê thị trường', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (140, 105, NULL, 8, '4.2. Lý luận của V.I.Lênin về đặc điểm kinh tế của độc quyền và độc quyền nhà nước trong nền kinh tế thị trường tư bản chủ nghĩa', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (141, 105, NULL, 9, '4.3. Biểu hiện mới của độc quyền, độc quyền nhà nước trong điều kiện ngày nay; vai trò lịch sử của chủ nghĩa tư bản', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (142, 105, NULL, 10, 'CHƯƠNG 5: KINH TẾ THỊ TRƯỜNG ĐỊNH HƯỚNG XÃ HỘI CHỦ NGHĨA VÀ CÁC QUAN HỆ LỢI ÍCH KINH TẾ Ở VIỆT NAM. 5.1. Kinh tế thị trường định hướng xã hội chủ nghĩa ở Việt Nam', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (143, 105, NULL, 11, '5.2. Hoàn thiện thế chế kinh tế thị trường định hướng xã hội chủ nghĩa ở Việt Nam', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (144, 105, NULL, 12, '5.3. Các quan hệ lợi ích kinh tế ở Việt Nam', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (145, 105, NULL, 13, 'CHƯƠNG 6: CÔNG NGHIỆP HÓA, HIỆN ĐẠI HÓA VÀ HỘI NHẬP KINH TẾ QUỐC TẾ CỦA VIỆT NAM. 6.1. Công nghiệp hóa, hiện đại hóa ở Việt Nam', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (146, 105, NULL, 14, '6.2. Hội nhập kinh tế quốc tế của Việt Nam', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (147, 105, NULL, 15, 'Tác động của hội nhập kinh tế quốc tế đến phát triển của Việt Nam. Phương hướng nâng cao hiệu quả hội nhập kinh tế quốc tế trong phát triển của Việt Nam', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (148, 79, NULL, 1, 'CHƯƠNG 1: ĐẢNG CỘNG SẢN VIỆT NAM RA ĐỜI VÀ LÃNH ĐẠO ĐẤU TRANH GIÀNH CHÍNH QUYỀN (1930 - 1945). ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (149, 79, NULL, 2, '1.1. Đảng Cộng sản Việt Nam ra đời và Cương lĩnh chính trị đầu tiên của Đảng Hội nghị thành lập Đảng Công sản Việt Nam và Cương lĩnh chính trị đầu tiên của Đảng. Ý nghĩa lịch sử của việc thành Đảng Cộng sản Việt Nam', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (151, 79, NULL, 3, 'Hội nghị thành lập Đảng Công sản Việt Nam và Cương lĩnh chính trị đầu tiên của Đảng. Ý nghĩa lịch sử của việc thành Đảng Cộng sản Việt Nam', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (153, 79, NULL, 4, '1.2. Lãnh đạo đấu tranh giành chính quyền (1930–1945)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (155, 79, NULL, 5, 'Phong trào dân chủ 1936-1939', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (156, 79, NULL, 6, 'Phong trào giải phóng dân tộc 1939-1945', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (157, 79, NULL, 7, 'Tính chất, ý nghĩa và kinh nghiệm của Cách mạng Tháng Tám năm 1945', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (158, 79, NULL, 8, 'CHƯƠNG 2: ĐẢNG LÃNH ĐẠO HAI CUỘC KHÁNG CHIẾN HOÀN THÀNH GIẢI PHÓNG DÂN TỘC, THỐNG NHẤT ĐẤT NƯỚC, (1945 – 1975). 2.1. Lãnh đạo xây dựng, bảo vệ chính quyền cách mạng và kháng chiến chống thực dân Pháp xâm lược (1945-1954)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (159, 79, NULL, 9, '2.1.2. Đường lối kháng chiến toàn quốc chống thực dân Pháp xâm lược và quá trình tổ chức thực hiện từ năm 1946 đến năm 1950', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (161, 79, NULL, 10, '2.1.3. Đẩy mạnh cuộc kháng chiến chống thực dân Pháp xâm lược và can thiệp Mỹ  đến thắng lợi từ  năm 1951 đến 1954', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (162, 79, NULL, 11, '2.1.4. Ý nghĩa lịch sử và kinh nghiệm lãnh đạo của Đảng trong kháng chiến chống Pháp và can thiệp Mỹ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (163, 79, NULL, 11, '2.2. Lãnh đạo xây dựng chủ nghĩa xã hội ở miền Bắc và kháng chiến chống đế quốc Mỹ xâm lược, giải phóng miền Nam, thống nhất đất nước (1954-1975). 2.2.1. Lãnh đạo cách mạng hai miền giai đoạn 1954 - 1965', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (164, 79, NULL, 12, '2.2.2. Lãnh đạo cách mạng cả nước giai đoạn 1965 - 1975. 2.2.3. Ý nghĩa và kinh nghiệm lãnh đạo của Đảng thời kỳ 1954-1975', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (165, 79, NULL, 13, 'CHƯƠNG 3:  ĐẢNG LÃNH ĐẠO CẢ NƯỚC QUÁ ĐỘ LÊN CNXH VÀ TIẾN HÀNH CÔNG CUỘC ĐỔI MỚI(1975 - 2018). 3.1. Lãnh đạo xây dựng chủ nghĩa xã hội và bảo vệ Tổ quốc (1975-1986)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (166, 79, NULL, 14, '3.2. Lãnh đạo công cuộc đổi mới, đẩy mạnh công nghiệp hóa, hiện đại hóa và hội nhập quốc tế (1986-2018)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (167, 79, NULL, 15, 'Tiếp tục công cuộc đổi mới, đẩy mạnh công nghiệp hóa, hiện đại hóa và hội nhập quốc tế (1996-2018). Thành tựu, kinh nghiệm của công cuộc đổi mới', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (177, 1, NULL, 1, 'CHƯƠNG 1. NHỮNG VẤN ĐỀ CƠ BẢN VỀ NHÀ NƯỚC VÀ PHÁP LUẬT. 1.1. Những vấn đề cơ bản về Nhà nước', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (178, 1, NULL, 2, '1.2. Những vấn đề cơ bản về pháp luật. 1.2.1. Nguồn gốc, bản chất, khái niệm và đặc trưng cơ bản của pháp luật', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (179, 1, NULL, 3, '1.2.1. Nguồn gốc, bản chất, khái niệm và đặc trưng cơ bản của pháp luật (tt). 1.2.2. Kiểu và hình thức pháp luật.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (180, 1, NULL, 4, 'CHƯƠNG 2: BỘ MÁY NHÀ NƯỚC CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM. 2.1. Các nguyên tắc tổ chức và hoạt động của bộ máy nhà nước CHXHCN Việt Nam. 2.2. Hệ thống cơ quan trong bộ máy nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (181, 1, NULL, 5, '2.2.2. Hệ thống cơ quan hành chính nhà nước. 2.2.3. Hệ thống cơ quan xét xử. 2.2.4. Hệ thống cơ quan kiểm sát. 2.2.5. Chủ tịch nước.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (182, 1, NULL, 6, 'CHƯƠNG 3. QUY PHẠM PHÁP LUẬT VÀ QUAN HỆ PHÁP LUẬT. 3.1. Quy phạm pháp luật', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (183, 1, NULL, 7, '3.2. Hệ thống các văn bản quy phạm pháp luật của nước Cộng hòa xã hội chủ nghĩa Việt Nam.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (184, 1, NULL, 8, '3.3. Quan hệ pháp luật', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (185, 1, NULL, 9, 'CHƯƠNG 4: THỰC HIỆN PHÁP LUẬT, VI PHẠM PHÁP LUẬT VÀ TRÁCH NHIỆM PHÁP LÝ. 4.1. Thực hiện pháp luật', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (186, 1, NULL, 10, '4.2. Vi phạm pháp luật', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (187, 1, NULL, 11, '4.3. Trách nhiệm pháp lý.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (188, 1, NULL, 12, 'CHƯƠNG 5: HỆ THỐNG PHÁP LUẬT, Ý THỨC PHÁP LUẬT, PHÁP CHẾ XÃ HỘI CHỦ NGHĨA. 5.1. Hệ thống pháp luật. 5.2. Ý thức pháp luật.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (189, 1, NULL, 13, '5.3. Pháp chế XHCN', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (190, 1, NULL, 14, 'CHƯƠNG 6. PHÁP LUẬT VỀ PHÒNG CHỐNG THAM NHŨNG. 6.1. Khái niệm, đặc điểm và các hành vi tham nhũng. 6.2. Nguyên nhân và hậu quả tham nhũng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (191, 1, NULL, 15, '6.3. Tầm quan trọng của công tác phòng, chống tham nhũng. 6.4. Trách nhiệm phòng chống tham nhũng.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (192, 96, NULL, 1, 'CHƯƠNG 1: KHÁI NIỆM, ĐỐI TƯỢNG, PHƯƠNG PHÁP NGHIÊN CỨU VÀ Ý NGHĨA HỌC TẬP MÔN TƯ TƯỞNG HỒ CHÍ MINH. CHƯƠNG 2: CƠ SỞ, QUÁ TRÌNH HÌNH THÀNH VÀ PHÁT TRIỂN TƯ TƯỞNG HỒ CHÍ MINH. 2.1. Cơ sở hình thành Tư tưởng Hồ Chí Minh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (194, 96, NULL, 3, '2.3. Giá trị của Tư tưởng Hồ Chí Minh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (195, 96, NULL, 4, 'CHƯƠNG 3: TƯ TƯỞNG HỒ CHÍ MINH VỀ ĐỘC LẬP DÂN TỘC VÀ CHỦ NGHĨA XÃ HỘI. 3.1. Tư tưởng Hồ Chí Minh về độc lập dân tộc. 3.2. Tư tưởng Hồ Chí Minh về chủ nghĩa xã hội và xây dựng chủ nghĩa xã hội ở Việt Nam. ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (196, 96, NULL, 5, '3.3. Tư tưởng Hồ Chí Minh về mối quan hệ giữa độc lập dân tộc và chủ nghĩa xã hội', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (197, 96, NULL, 6, '3.4. Vận dụng Tư tưởng Hồ Chí Minh về độc lập dân tộc gắn liền với chủ nghĩa xã hội trong sự nghiệp cách mạng Việt Nam giai đoạn hiện nay.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (198, 96, NULL, 10, '5.2. Tư tưởng Hồ Chí Minh về đoàn kết quốc tế', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (199, 96, NULL, 11, '5.3. Vận dụng Tư tưởng Hồ Chí Minh về đại đoàn kết toàn dân tộc và đoàn kết quốc tế trong giai đoạn hiện nay', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (200, 96, NULL, 12, 'CHƯƠNG 6: TƯ TƯỞNG HỒ CHÍ MINH VỀ VĂN HOÁ, ĐẠO ĐỨC, CON NGƯỜI. 6.1.Tư tưởng Hồ Chí Minh về văn hoá.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (201, 96, NULL, 13, '6.2. Tư tưởng Hồ Chí Minh về đạo đức', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (202, 96, NULL, 14, '6.3. Tư tưởng Hồ Chí Minh về con người', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (203, 96, NULL, 15, '6.4. Xây dựng văn hóa, đạo đức, con người Việt Nam hiện nay theo Tư tưởng Hồ Chí Minh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (204, 96, NULL, 2, '2.2. Quá trình hình thành và phát triển Tư tưởng Hồ Chí Minh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (206, 96, NULL, 7, 'CHƯƠNG 4: TƯTƯỞNG HỒ CHÍ MINH VỀ ĐẢNG CỘNG SẢN VIỆT NAM VÀ NHÀ NƯỚC CỦA NHÂN DÂN,DO NHÂN DÂN, VÌ NHÂN DÂN. 4.1. Tư tưởng Hồ Chí Minh về Đảng Cộng sản Việt Nam', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (207, 96, NULL, 8, '4.2. Tư tưởng Hồ Chí Minh về Nhà nước Việt Nam. 4.3. Vận dụng Tư tưởng Hồ Chí Minh vào công tác xây dựng Đảng và xây dựng nhà nước', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (208, 96, NULL, 9, 'CHƯƠNG 5: TƯ TƯỞNG HỒ CHÍ MINH VỀ ĐẠI ĐOÀN KẾT DÂN TỘC VÀ ĐOÀN KẾT QUỐC TẾ. 5.1. Tư tưởng Hồ Chí Minh về đại đoàn kết toàn dân tộc.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (209, 7, NULL, 1, 'Chương 1: MA TRẬN - ĐỊNH THỨC. 1.1. Khái niệm mở đầu về ma trận', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (210, 7, NULL, 2, '1.2. Định thức', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (211, 7, NULL, 3, '1.3. Hạng của ma trận. ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (212, 7, NULL, 4, '1.4. Ma trận nghịch đảo', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (213, 7, NULL, 5, 'Chương 2: HỆ PHƯƠNG TRÌNH TUYẾN TÍNH. 2.1. Hệ phương trình tuyến tính', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (214, 7, NULL, 6, '2.2. Các phương pháp giải hệ phương trình tuyến tính', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (215, 7, NULL, 7, 'Chương 3: KHÔNG GIAN VECTƠ. 3.1. Khái niệm về không gian vectơ.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (216, 7, NULL, 8, '3.2. Không gian con. Hệ sinh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (217, 7, NULL, 9, '3.3. Hạng của một họ vectơ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (218, 7, NULL, 10, '3.4. Bài toán đổi cơ sở', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (219, 7, NULL, 11, '3.5. Ánh xạ tuyến tính', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (220, 7, NULL, 12, 'Bài tập chương 3', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (221, 7, NULL, 13, 'Chương 4: DẠNG TOÀN PHƯƠNG. 4.1. Định nghĩa. 4.2. Hạng của dạng toàn phương. 4.3. Dạng toàn phương chính tắc', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (222, 7, NULL, 14, '4.4. Đưa dạng toàn phương về chính tắc', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (223, 7, NULL, 15, '4.5. Phân loại dạng toàn phương', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (224, 55, NULL, 1, 'CHƯƠNG 1: BIẾN CỐ VÀ XÁC SUẤT. 1.1. Nhắc lại về đại số tổ hợp. 1.2. Phép thử và biến cố', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (225, 55, NULL, 2, '1.3. Xác suất của biến cố', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (226, 55, NULL, 3, '1.4.Các công thức về xác suất ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (227, 55, NULL, 4, 'Bài tập và thảo luận', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (228, 55, NULL, 5, 'Bài tập và thảo luận', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (229, 55, NULL, 6, 'CHƯƠNG 2: BIẾN NGẪU NHIÊN VÀ CÁC LUẬT PHÂN PHỐI XÁC SUẤT. 2.1. Biến ngẫu nhiên. 2.2. Hàm phân phối xác suất của biến ngẫu nhiên', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (230, 55, NULL, 7, '2.3.Luật phân phối xác suất. 2.4. Các tham số đặc trưng của biến ngẫu nhiên', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (231, 55, NULL, 8, '2.5.Các luật phân phối xác suất thông dụng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (232, 55, NULL, 9, 'Bài tập và thảo luận', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (233, 55, NULL, 10, 'Kiểm tra giữa kì ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (234, 55, NULL, 11, 'CHƯƠNG 3: LÝ THUYẾT CHỌN MẪU. 3.1. Lý thuyết chọn mẫu. 3.2. Các phương pháp sắp xếp dấu hiệu thống kê', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (235, 55, NULL, 12, '3.3. Hàm phân phối thực nghiệm. 3.4. Các tham số đặc trưng của mẫu', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (236, 55, NULL, 13, 'CHƯƠNG 4. LÍ THUYẾT ƯỚC LƯỢNG VÀ KIỂM ĐỊNH. 4.1. Mở đầu. 4.2. Các tiêu chuẩn ước lượng.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (237, 55, NULL, 14, '4.3. Khoảng ước lượng đối xứng. 4.4. Kiểm định giá trị trung bình. ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (238, 55, NULL, 15, 'Bài tập và thảo luận', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (239, 36, NULL, 1, 'Giới thiệu học phần. Chương 1. Giới thiệu về phát triển hướng đối tượng. Chương 2. Tổng quan về ngôn ngữ mô hình hóa hợp nhất (UML). Chương 3. UML và quy trình phát triển phần mềm.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (241, 36, NULL, 2, 'Chương 4. Mô hình hóa yêu cầu', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (242, 36, NULL, 3, 'Hướng dẫn sinh viên\r\nlàm bài tập Chương 4.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (243, 36, NULL, 4, 'Bài tập nhóm: Mô hình\r\nhóa yêu cầu', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (245, 36, NULL, 5, 'Chương 5. Mô hình hóa\r\ncấu trúc tĩnh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (246, 36, NULL, 6, 'Bài tập nhóm: Biểu đồ\r\nlớp mức phân tích', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (247, 36, NULL, 7, 'Hướng dẫn sinh viên làm bài tập Chương 5. Chương 6. Mô hình hóa hành vi', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (248, 36, NULL, 8, 'Hướng dẫn sinh viên làm bài tập Chương 6. Bài tập nhóm: Biểu đồ hoạt động và biểu đồ trạng thái', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (249, 36, NULL, 9, 'Đánh giá giữa kỳ. Bài tập nhóm: Biểu đồ tương tác', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (250, 36, NULL, 10, 'Chương 7. Mô hình hóa kiến trúc. Chương 8. Các nguyên tắc thiết kế GRASP', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (251, 36, NULL, 11, 'Hướng dẫn sinh viên làm bài tập Chương 7. Bài tập nhóm: Mô hình hóa kiến trúc ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (252, 36, NULL, 12, 'Chương 9. Cài đặt. Chương 10. Ứng dụng. Các thành viên của nhóm trình bày báo cáo bài tập nhóm', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (290, 49, NULL, 1, 'Chương 1.  TẬP HỢP - ÁNH XẠ VÀ   SỐ PHỨC. 1.1. Tập hợp. 1.2. Ánh xạ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (291, 49, NULL, 2, '1.3. Số phức', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (292, 49, NULL, 3, 'Chương 2: HÀM SỐ MỘT BIẾN SỐ - GIỚI HẠN VÀ LIÊN TỤC - ĐẠO HÀM VÀ VI PHÂN. 2.1. Các khái niệm cơ bản về hàm số một biến số. 2.2. Giới hạn của dãy số', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (293, 49, NULL, 4, '2.3. Giới hạn của hàm số. 2.4. Vô cùng bé và vô cùng lớn. 2.5.  Hàm số liên tục', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (294, 49, NULL, 5, '2.6. Đạo hàm. 2.7. Vi phân', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (295, 49, NULL, 6, '2.8. Các định lý về hàm khả vi. Bài tập chương 2', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (296, 49, NULL, 7, 'Chương 3: PHÉP TÍNH TÍCH PHÂN CỦA HÀM SỐ MỘT BIẾN SỐ. 3.1. Tích phân bất định. 3.2. Tích phân xác định. 3.3. Một số ứng dụng hình học của tích phân xác định', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (297, 49, NULL, 8, '3.4. Tích phân suy rộng. Bài tập chương 3', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (298, 49, NULL, 9, 'Chương 4: CHUỖI. 4.1. Đại cương về chuỗi. 4.2. Chuỗi số dương', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (299, 49, NULL, 10, '4.3. Chuỗi có số hạng với dấu bất kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (300, 49, NULL, 11, '4.4. Chuỗi lũy thừa. Bài tập chương 4', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (301, 49, NULL, 12, 'Chương 5: HÀM SỐ HAI BIẾN. 5.1.. Khái niệm mở đầu', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (302, 49, NULL, 13, '5.2. Đạo hàm riêng. Vi phân toàn phần', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (303, 49, NULL, 14, '5.3. Cực trị hàm hai biến', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (304, 49, NULL, 15, 'Bài tập chương 5', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (305, 100, NULL, 1, 'Bài 1.Giới thiệu', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (306, 100, NULL, 2, 'Bài 2. Xử lý ảnh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (307, 100, NULL, 3, 'Bài 3. Phát hiện đặc trưng ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (308, 100, NULL, 4, 'Bài 4. Phân đoạn ảnh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (309, 100, NULL, 5, 'Kiểm tra giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (310, 100, NULL, 6, 'Bài 5. Cấu trúc chuyển động ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (311, 100, NULL, 7, 'Bài 6. Nhiếp ảnh điện toán ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (312, 100, NULL, 8, 'Bài 7. Nhận dạng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (313, 100, NULL, 9, 'Báo cáo và thuyết trình bài tập nhóm', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (314, 100, NULL, 10, 'Thi kết thúc học phần', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (315, 99, NULL, 1, 'Giới thiệu học phần. Chương 1. Tổng quan về tương tác người máy', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (316, 99, NULL, 2, 'Chương 2. Tâm lý người dùng và giao diện phần mềm. 2.1. Tầm quan trọng của người dung. 2.2. Các thói quen của người dùng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (317, 99, NULL, 3, 'Chương 2. Tâm lý người dùng và giao diện phần mềm. 2.2 Tâm lý người dung. 2.3 Bài tập', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (318, 99, NULL, 4, 'Chương 3. Tổ chức nội dung giao diện. 3.1 Kiến trúc thông tin. 3.2 Cấu trúc vật lý', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (319, 99, NULL, 5, 'Chương 3. Tổ chức nội dung giao diện. 3.3 Các mẫu thiết kế. 3.4 Bài tập', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (320, 99, NULL, 6, 'Chương 4. Định hướng trong giao diện. 4.1 Khái niệm và chi phí định hướng trong giao diện', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (321, 99, NULL, 7, 'Chương 4. Định hướng trong giao diện. 4.2 Các mô hình định hướng. 4.3 Bài tập', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (323, 99, NULL, 8, 'Chương 5. Bố cục giao diện. 5.1 Khái niệm bố cục giao diện. 5.2 Các thành phần cơ bản', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (324, 99, NULL, 9, 'Chương 5. Bố cục giao diện. 5.3 Các mẫu thiết kế. 5.4 Bài tập', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (325, 99, NULL, 10, 'Chương 6. Các tác vụ giao diện. 6.1 Khái niệm tác vụ trên giao diện. 6.2 Các mẫu thiết kế.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (326, 99, NULL, 11, 'Chương 6. Các tác vụ giao diện. 6.2 Các mẫu thiết kế. 6.3 Bài tập.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (327, 99, NULL, 12, 'Chương 7. Đồ họa thông tin giao diện. 7.1 Đồ họa thông tin giao diện. 7.2 Vấn đề của đồ họa thông tin giao diện. 7.3 Các mẫu thiết kế', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (328, 99, NULL, 13, 'Chương 7. Đồ họa thông tin giao diện. 7.3 Các mẫu thiết kế. 7.4 Bài tập', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (329, 99, NULL, 14, 'Chương 8. Giao diện thu thập dữ liệu người dung. 8.1 Quy tắc thiết kế. 8.2 Các mẫu thiết kế.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (330, 99, NULL, 15, 'Chương 8. Giao diện thu thập dữ liệu người dung. 8.2 Các mẫu thiết kế. 8.3 Bài tập. Ôn tập', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (331, 97, NULL, 1, 'Chương 1. Tổng quan về phân tích dữ liệu', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (332, 97, NULL, 2, 'Chương 2. Ngôn ngữ R', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (333, 97, NULL, 3, 'Chương 2. Ngôn ngữ R (tiếp theo)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (334, 97, NULL, 4, 'Chương 3. Phân tích dữ liệu bằng R. 3.1. Phân tích thống kê mô tả', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (335, 97, NULL, 5, '3.2. Phân tích hồi quy tuyến tính', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (336, 97, NULL, 6, '3.3. Phân tích phương sai', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (337, 97, NULL, 7, '3.4. Phân tích hồi qui logistic ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (338, 97, NULL, 8, '3.5. Phân tích dữ liệu Text (Text analysis)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (339, 108, NULL, 1, 'Bài 1. Tổng quan về đồ họa', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (340, 108, NULL, 2, 'Bài 2. Lập trình đồ họa với OpenGL', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (341, 108, NULL, 3, 'Bài 3. Kỹ thuật đồ họa 2D', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (342, 108, NULL, 5, 'Bài 4. Kỹ thuật đồ họa 3D', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (343, 108, NULL, 7, 'Bài 5. Biểu diễn đường và mặt cong', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (344, 108, NULL, 8, 'Bài 6. Các kỹ thuật nâng cao', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (345, 108, NULL, 9, 'Bài 7. Hoạt hình ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (346, 108, NULL, 10, 'Bài 8. Thực tại ảo', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (347, 71, NULL, 1, 'Bài 1. Giới thiệu về TTNT ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (348, 71, NULL, 2, 'Bài 2. Giải quyết vấn đề', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (349, 71, NULL, 3, 'Bài 3. Biểu diễn và xử lý tri thức', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (350, 71, NULL, 4, 'Bài 4. Giới thiệu về Học máy ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (351, 71, NULL, 5, 'Bài 5. Ứng dụng Trí tuệ nhân tạo ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (352, NULL, '1133', 1, 'Chương 1. Làm quen với Java và môi trường lập trình Eclipse', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (353, NULL, '1133', 2, 'Chương 2. Các thành phần cơ bản và lệnh điều khiển của Java', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (354, NULL, '1133', 3, 'Chương 3. Phương thức, mảng và tham chiếu trong Java', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (355, NULL, '1133', 4, 'Chương 4. Lập trình hướng đối tượng với Java', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (356, NULL, '1133', 5, 'Chương 5. Xử lý biệt lệ (Exception handling)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (357, NULL, '1133', 6, 'Chương 6. Lập trình giao diện với AWT, Swing và JavaFX (GUI programming)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (358, NULL, '1133', 7, 'Chương 7. Lập trình kết nối cơ sở dữ liệu', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (359, NULL, '1135', 1, 'Chương 1. Giới thiệu về công nghệ OWC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (360, NULL, '1135', 2, 'Chương 2. Giới thiệu về công nghệ Li-Fi (VLC)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (361, NULL, '1135', 3, 'Chương 3. Thiết bị chiếu sáng và truyền dữ liệu ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (362, NULL, '1135', 4, 'Chương 4. Thiết bị thu ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (363, NULL, '1135', 5, 'Chương 5. Kênh truyền VLC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (364, NULL, '1135', 6, 'Chương 6. Mô phỏng hệ thống VLC. 6.1 Giới thiệu MATLAB. 6.2 Ứng dụng MATLAB trong biểu diễn tín hiệu và mô phỏng hệ thống', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (365, NULL, '1135', 7, 'Chương 6. Mô phỏng hệ thống VLC. 6.3 Mô phỏng hệ thống VLC đơn trên MATLAB', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (366, NULL, '1135', 8, 'Kiểm tra giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (367, NULL, '1135', 9, 'Chương 7. Kỹ thuật điều chế sử dụng trong VLC. 7.1 OOK. 7.2 OFDM. 7.3 PWM. 7.4 CSK', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (368, NULL, '1135', 10, 'Chương 7. Kỹ thuật điều chế sử dụng trong VLC. 7.4 Mô phỏng các kỹ thuật điều chế sử dụng trong VLC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (369, NULL, '1135', 11, 'Bài thực hành số 1. Khảo sát thực nghiệm hệ thống VLC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (370, NULL, '1135', 12, 'Chương 8. Hệ thống MIMO VLC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (371, NULL, '1135', 13, 'Chương 9. Mô phỏng hệ thống MIMO-VLC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (372, NULL, '1135', 14, 'Bài thực hành số 2. Kết nối hệ thống VLC vào PC tryền đa phương tiện', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (373, NULL, '1135', 15, 'Thảo luận & Ôn tập', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (374, 101, NULL, 1, 'Chương 1. Tổng quan về hệ thống nhúng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (375, 101, NULL, 2, 'Chương 2. Các thành phần của hệ thống nhúng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (376, 101, NULL, 3, 'Chương 3. Nền tảng phần cứng thông dụng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (377, 101, NULL, 4, 'Chương 4. Lập trình hệ thống nhúng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (378, 101, NULL, 5, 'Kiểm tra giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (379, 101, NULL, 6, 'Chương 5. Hệ điều hành thời gian thực', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (380, 101, NULL, 7, 'Chương 6. Lý thuyết thiết kế hệ thống nhúng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (381, 101, NULL, 8, 'Chương 7. Ví dụ về hệ thống nhúng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (382, 34, NULL, 1, 'Chương 1. Các hệ thống số và mã', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (383, 34, NULL, 2, 'Chương 2. Đại số Boole và các cổng luận lý', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (384, 34, NULL, 3, 'Chương 3. Mạch tổ hợp', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (385, 34, NULL, 4, 'Chương 4. Flip-Flop và mạch tuần tự', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (386, 34, NULL, 5, 'Kiểm tra giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (387, 34, NULL, 6, 'Chương 5. Các phép toán và mạch', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (388, 34, NULL, 7, 'Chương 6. Bộ đếm và thanh ghi', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (389, 34, NULL, 8, 'Chương 7. Thiết kế mạch tổ hợp sử dụng vi mạch MSI', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (390, 34, NULL, 9, 'Ôn tập', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (391, 42, NULL, 1, 'PHẦN 1: Tổng quan về thiết kế đồ họa Vector. Bài 1. Tìm hiểu về không gian làm việc', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (392, 42, NULL, 2, 'Bài 2. Các công cụ tạo hình cơ bản, phức tạp và phương pháp hiệu chỉnh. Bài 3. Màu sắc trong Illustrator', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (393, 42, NULL, 3, 'Bài 4. Công cụ xử lý văn bản', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (394, 42, NULL, 4, 'Bài 5. Quản lý đối tượng trong Illustrator ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (395, 42, NULL, 5, 'Bài 6. Cách sử dụng các nét bút', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (396, 42, NULL, 6, 'Bài 7. Kết hợp các hình cơ bản - Kỹ thuật tạo mặt nạ cho đối tượng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (397, 42, NULL, 7, 'Bài 8. Hiệu ứng trong Illustrator. Kiểm tra giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (398, 42, NULL, 8, 'PHẦN 2: Tổng quan về thiết kế video. Bài 1. Tổng quan về hình hiệu- motions graphic. Bài 2. Tổng quan phần mềm thiết kế chuyển động hình ảnh và văn bản After effects', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (399, 42, NULL, 9, 'Bài 3. Kịch bản (storyboard)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (400, 42, NULL, 10, 'Bài 4. Quản lý- biên tập dữ liệu', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (401, 42, NULL, 11, 'Bài 5: Làm việc với hình ảnh và Vector', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (402, 42, NULL, 12, 'Bài 6: Tín hiệu văn bản', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (403, 42, NULL, 13, 'Bài 7: Kỹ xảo âm thanh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (404, 42, NULL, 14, 'Bài 8: Hiệu ứng nâng cao', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (405, 42, NULL, 15, 'Thi cuối kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (406, 35, NULL, 1, 'Giới thiệu học phần.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (407, 35, NULL, 2, 'Chương 1. Mở đầu', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (408, 35, NULL, 3, 'Chương 2. Tầng vật lý', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (409, 35, NULL, 4, 'Chương 3. Mạng cục bộ LAN', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (410, 35, NULL, 5, 'Chương 4. Tầng mạng (Network/ Internet Layer)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (411, 35, NULL, 6, 'Chương 4. Tầng mạng (Network/ internet layer) (tiếp tục)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (412, 35, NULL, 7, 'Bài tập nhóm: Thiết kế cơ sở hạ tầng LAN cơ bản', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (413, 35, NULL, 8, 'Kiểm tra giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (414, 35, NULL, 9, 'Chương 5. Tầng giao vận', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (415, 35, NULL, 10, 'Chương 6. Họ giao thức TCP/IP', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (416, 35, NULL, 11, 'Chương 6. Họ giao thức TCP/IP (tiếp tục)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (417, 35, NULL, 12, 'Chương 7. Tầng ứng dụng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (418, 35, NULL, 13, 'Chương 7. Tầng ứng dụng (tiếp tục)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (419, 35, NULL, 14, 'Bài tập nhóm: Triển khai các dịch vụ trên liên mạng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (420, 35, NULL, 15, 'Trình bày bài tập nhóm', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (421, 70, NULL, 1, 'Chương 1: CÁC KHÁI NIỆM CƠ BẢN VỀ QUẢN TRỊ MẠNG', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (422, 70, NULL, 2, 'Chương 1: CÁC KHÁI NIỆM CƠ BẢN VỀ QUẢN TRỊ MẠNG (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (423, 70, NULL, 3, 'Chương 1: CÁC KHÁI NIỆM CƠ BẢN VỀ QUẢN TRỊ MẠNG (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (424, 70, NULL, 4, 'Chương 1: CÁC KHÁI NIỆM CƠ BẢN VỀ QUẢN TRỊ MẠNG (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (425, 70, NULL, 5, 'Chương 2: QUẢN TRỊ MẠNG VỚI WINDOWS SERVER ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (426, 70, NULL, 6, 'Chương 2: QUẢN TRỊ MẠNG VỚI WINDOWS SERVER (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (427, 70, NULL, 7, 'Chương 2: QUẢN TRỊ MẠNG VỚI WINDOWS SERVER (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (428, 70, NULL, 8, 'Chương 3: MỘT SỐ DỊCH VỤ CƠ BẢN TRÊN SERVER', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (429, 70, NULL, 9, 'Chương 3: MỘT SỐ DỊCH VỤ CƠ BẢN TRÊN SERVER (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (430, 70, NULL, 10, 'Chương 3: MỘT SỐ DỊCH VỤ CƠ BẢN TRÊN SERVER (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (431, 70, NULL, 11, 'Chương 3: MỘT SỐ DỊCH VỤ CƠ BẢN TRÊN SERVER (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (432, 70, NULL, 12, 'Chương 4: BỘ ĐỊNH TUYẾN', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (433, 70, NULL, 13, 'Chương 5. DỊCH VỤ TRUY CẬP TỪ XA', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (434, 70, NULL, 14, 'Chương 5. DỊCH VỤ TRUY CẬP TỪ XA (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (435, 70, NULL, 15, 'Chương 6. BẢO MẬT HỆ THỐNG MẠNG ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (437, 38, NULL, 1, 'Unit 1. Working in the IT industry', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (438, 38, NULL, 2, 'Unit 1. Working in the IT industry (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (439, 38, NULL, 3, 'Unit 2. Computer systems  ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (440, 38, NULL, 4, 'Unit 2. Computer systems (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (441, 38, NULL, 5, 'Unit 3. Websites', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (442, 38, NULL, 6, 'Unit 3. Websites (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (443, 38, NULL, 7, 'Unit 4. Databases', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (444, 38, NULL, 8, 'Unit 4. Databases (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (445, 38, NULL, 9, 'Unit 5. E-commerce', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (446, 38, NULL, 10, 'Unit 5. E-commerce (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (447, 38, NULL, 11, 'Unit 6. Network systems', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (448, 38, NULL, 12, 'Unit 6. Network systems (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (449, 38, NULL, 13, 'Unit 7. IT support', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (450, 38, NULL, 14, 'Unit 7. IT support (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (452, 38, NULL, 15, 'Unit 8. IT Security and safety', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (453, 13, NULL, 1, 'Unit 1. Computer applications ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (454, 13, NULL, 2, 'Unit 1. Computer applications (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (455, 13, NULL, 3, 'Unit 2. Computer essentials  ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (456, 13, NULL, 4, 'Unit 2. Computer essentials  (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (457, 13, NULL, 5, 'Unit 3. Inside the system', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (458, 13, NULL, 6, 'Unit 3. Inside the system(continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (459, 13, NULL, 7, 'Unit 4. Bits And Bytes', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (460, 13, NULL, 8, 'Unit 4. Bits And Bytes (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (461, 13, NULL, 9, 'Unit 5. Buying A Computer', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (462, 13, NULL, 10, 'Unit 5. Buying A Computer (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (463, 13, NULL, 11, 'Unit 6. Type and click!', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (464, 13, NULL, 12, 'Unit 6. Type and click! (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (465, 13, NULL, 13, 'Unit 7. Capture Your Favorite Image', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (466, 13, NULL, 14, 'Unit 7. Capture Your Favorite Image (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (467, 13, NULL, 15, 'Unit 8. Viewing The Output', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (469, 65, NULL, 1, '1. Tổng quan về Robot. 1.1 Sơ lược về quá trình phát triển. 1.2 Các khái niệm về Robot. 1.3 Phân loại Robot', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (470, 65, NULL, 2, '1. Tổng quan về Robot. 1.4 Ứng dụng của Robot. 1.5 Một số Robot cơ bản', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (471, 65, NULL, 3, '2. Giới thiệu về xe tự hành. 2.1 Các khái niệm cơ bản. 2.2 Thế nào là dò đường', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (472, 65, NULL, 4, '2. Giới thiệu về xe tự hành. 2.3 Dò đường dựa trên mô hình', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (473, 65, NULL, 5, '3. Thiết kế và thực hiện robot tự hành dò vạch (black line)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (474, 65, NULL, 6, '4. Thiết kế và thực hiện robot tự hành sử dụng cảm biến hồng ngoại hoặc cảm biến siêu âm để tránh vật thể.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (475, 65, NULL, 7, '5. Mở rộng thiết kế với điều khiển trên Android app, iOS app hoặc web apps qua bluetooth hoặc wifi module.', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (476, 65, NULL, 8, 'Thiết kế và thực hiện robot tự hành với SLAM, Navigation with ROS', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (477, 65, NULL, 9, 'Thiết kế và thực hiện robot tự hành với Raspi Camera', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (478, 65, NULL, 10, 'Mô phỏng navigation with LIDAR sensor trên Gazebo', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (479, 31, NULL, 1, '1. Get started fast with PHP & MySQL', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (480, 31, NULL, 2, '2. Master PHP Programming. How to work with form data. How to code control statements', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (481, 31, NULL, 3, '2. Master PHP Programming. How to work with dates. How to work with arrays', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (482, 31, NULL, 4, '2. Master PHP Programming. How to work with cookie. How to work with session', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (483, 31, NULL, 5, '2. Master PHP Programming. How to work with functions', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (484, 31, NULL, 6, '2. Master PHP Programming. How to work with objects. How to work with regular expression, handle exception', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (485, 31, NULL, 7, '3. Master MySQL Programming. How to design a database', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (486, 31, NULL, 8, '3. Master MySQL Programming. How to using SQL to create a MySQL database', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (487, 31, NULL, 9, '3. Master MySQL Programming. Professional PHP for working with MySQL', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (488, 31, NULL, 10, '3. Master MySQL Programming. A database-driven website', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (489, 31, NULL, 11, '4. Master the advanced skills for building websites. How to create secure websites', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (490, 31, NULL, 12, '4. Master the advanced skills for building websites. How to send email and access other websites. How to work with files, uploads and images', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (491, 31, NULL, 13, '4. Master the advanced skills for building websites Laravel Framework NodeJS Open source PHP Wordpress, Magento, Opencart', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (492, 31, NULL, 14, 'Hướng dẫn đồ án môn học', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (493, 25, NULL, 1, 'Chương 1: Những vấn đề chung về giao tiếp trong kinh doanh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (494, 25, NULL, 2, 'Phong cách giao tiếp. Một số rào cản trong giao tiếp kinh doanh. Một số nguyên tắc giao tiếp trong kinh doanh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (495, 25, NULL, 3, 'Chương 2. Ấn tượng ban đầu trong giao tiếp', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (496, 25, NULL, 4, 'Quá trình hình thành ấn tượng ban đầu', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (497, 25, NULL, 5, 'Chương 3. Các kỹ năng giao tiếp chủ yếu trong kinh doanh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (498, 25, NULL, 6, 'Kỹ năng giới thiệu và tự giới thiệu', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (499, 25, NULL, 7, 'Kỹ năng giao tiếp qua điện thoại', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (500, 25, NULL, 8, 'Kỹ năng viết trong kinh doanh. Kiểm tra giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (501, 25, NULL, 9, 'Kỹ năng viết tin. Kỹ năng viết báo cáo', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (502, 25, NULL, 10, 'Chương 4. Kỹ năng đàm phán trong kinh doanh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (503, 25, NULL, 11, 'Quy trình đàm phán trong kinh doanh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (504, 25, NULL, 12, 'Kỹ năng làm chủ buổi đàm phán', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (505, 25, NULL, 13, 'Chương 5. Giao tiếp ứng dụng trong kinh doanh', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (506, 25, NULL, 14, 'Kỹ năng giao tiếp trong các bữa tiệc', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (507, 25, NULL, 15, 'Kỹ năng đón tiếp và chăm sóc khách hàng trong sự kiện', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (508, 107, NULL, 1, 'Giới thiệu tổng quan môn học. Chương 1: Những vấn đề cơ bản về hành vi người tiêu dùng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (509, 107, NULL, 2, 'Chương 2: Các yếu tố tâm lý tác động đến hành vi người tiêu dùng. Động cơ người tiêu dùng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (510, 107, NULL, 3, 'Động cơ, khả năng và cơ hội. ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (511, 107, NULL, 4, 'Nhận thức. Khái niệm về nhận thức. Tiến trình nhận thức', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (512, 107, NULL, 5, 'Kiến thức và trí nhớ. ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (513, 107, NULL, 6, 'Thái độ. ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (514, 107, NULL, 7, 'Chương 3: Tiến trình ra quyết định. Các loại tiến trình ra quyết định. Tiến trình ra quyết định', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (515, 107, NULL, 8, 'Tìm kiếm thông tin. Tiến trình đánh giá và ra quyết định. Tiến trình sau quyết định', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (516, 107, NULL, 9, 'Chương 4: Các yếu tố cá nhân ảnh hưởng đến hành vi người tiêu dùng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (517, 107, NULL, 10, 'Chương 5: Các yếu tố văn hóa, xã hội ảnh hưởng đến hành vi người tiêu dùng', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (518, 107, NULL, 11, 'Chương 6: Hành vi người tiêu dùng online', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (519, 94, NULL, 1, 'Chương 1. Tổng quan về kinh tế học. 1.1 Định nghĩa. 1.2 Các mô hình kinh tế', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (520, 94, NULL, 2, 'Chương 1. Tổng quan về kinh tế học. 1.3 Lý thuyết lựa chọn kinh tế. 1.4 Đường giới hạn khả năng sản xuất (PPF)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (521, 94, NULL, 3, 'Chương 2: Cung, cầu và độ co giãn. 2.1 Cầu. 2.2 Cung', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (522, 94, NULL, 4, 'Chương 2: Cung, cầu và độ co giãn. 2.3 Cân bằng thị trường. 2.4 Sự can thiệp của Chính phủ vào thị trường', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (523, 94, NULL, 5, 'Chương 2: Cung, cầu và độ co giãn. 2.5 Độ co giãn', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (524, 94, NULL, 6, 'Bài tập Chương 2', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (525, 94, NULL, 7, 'Chương 3: Lý thuyết hành vi người tiêu dung. 3.1 Lý thuyết hữu ích. 3.2 Lý thuyết đẳng ích', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (526, 94, NULL, 8, 'Chương 3: Lý thuyết hành vi người tiêu dung. 3.3 Đường ngân sách. 3.4 Sự lựa chọn tối ưu của người tiêu dung', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (527, 94, NULL, 9, 'Bài tập Chương 3', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (528, 94, NULL, 10, 'Thi giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (529, 94, NULL, 11, 'Chương 4: Lý thuyết hành vi người sản xuất. 4.1 Lý thuyết sản xuất', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (530, 94, NULL, 12, 'Chương 4: Lý thuyết hành vi người sản xuất. 4.2 Lý thuyết chi phí. 4.3 Quyết định sản xuất trong ngắn hạn', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (531, 94, NULL, 13, 'Bài tập Chương 4', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (532, 94, NULL, 14, 'Chương 5: Cạnh tranh và độc quyền. 5.1 Thị trường cạnh tranh hoàn hảo. 5.2 Thị trường độc quyền', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (533, 94, NULL, 15, 'Bài tập Chương 5', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (536, 2, NULL, 1, 'Chapter 1. The foundation of Business', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (537, 2, NULL, 2, 'Chapter 1. The foundation of Business (cont’d)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (538, 2, NULL, 3, 'Chapter 2. Business Ethics and Social Responsibility', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (539, 2, NULL, 4, 'Chapter 2. Business Ethics and Social Responsibility (cont’d)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (540, 2, NULL, 5, 'Chapter 3. Business in a Global Environment', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (541, 2, NULL, 6, 'Chapter 3. Business in a Global Environment (cont’d)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (542, 2, NULL, 7, 'Mid-term Test', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (543, 2, NULL, 8, 'Chapter 4: The Challenges of Starting a Business', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (544, 2, NULL, 9, 'Chapter 4: The Challenges of Starting a Business (cont’d)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (545, 2, NULL, 10, 'Chapter 5 Selecting a form of Business Ownership', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (546, 2, NULL, 11, 'Chapter 6 Managing for Business Success ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (547, 2, NULL, 12, 'Chapter 7 Product Design and Development', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (548, 2, NULL, 13, 'Chapter 7 Product Design and Development (cont’d)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (549, 2, NULL, 14, 'Chapter 8 Managing Information and Technology', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (550, 2, NULL, 15, 'Chapter 8 Managing Information and Technology (cont’d)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (551, 109, NULL, 1, 'Unit 1 – Management', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (552, 109, NULL, 2, 'Unit 1 – Management (Con’t)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (553, 109, NULL, 3, 'Unit 2 – Company Structure', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (554, 109, NULL, 4, 'Unit 2 – Company Structure (Con’t)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (555, 109, NULL, 5, 'Unit 3 – Work and motivation ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (556, 109, NULL, 6, 'Unit 3 – Work and motivation (Con’t)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (557, 109, NULL, 7, 'Unit 4 – Recruitment ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (558, 109, NULL, 8, 'Unit 4 – Recruitment (Con’t)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (559, 109, NULL, 9, 'Unit 5 – Managing across cultures ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (560, 109, NULL, 10, 'Unit 5 – Managing across cultures (Con’t)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (561, 109, NULL, 11, 'Unit 6 – Women in business', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (562, 109, NULL, 12, 'Unit 6 – Women in business (Con’t)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (563, 14, NULL, 1, 'Chương 1. Tổng quan về máy tính', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (564, 14, NULL, 2, 'Chương 2. Hệ điều hành Windows', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (565, 14, NULL, 3, 'Chương 3. Mạng máy tính và internet', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (566, 14, NULL, 4, 'Chương 4. Sử dụng Microsoft Word', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (567, 14, NULL, 5, 'Chương 4. Sử dụng Microsoft Word (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (568, 14, NULL, 6, 'Chương 4. Sử dụng Microsoft Word (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (569, 14, NULL, 7, 'Chương 4. Sử dụng Microsoft Word (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (570, 14, NULL, 8, 'Chương 4. Sử dụng Microsoft Word (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (571, 14, NULL, 9, 'Chương 5. Sử dụng Microsoft PowerPoint', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (572, 14, NULL, 10, 'Chương 6. Sử dụng Microsoft Excel', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (573, 14, NULL, 11, 'Chương 6. Sử dụng Microsoft Excel (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (574, 14, NULL, 12, 'Chương 6. Sử dụng Microsoft Excel (tt) ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (575, 14, NULL, 13, 'Chương 6. Sử dụng Microsoft Excel (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (576, 14, NULL, 14, 'Chương 6. Sử dụng Microsoft Excel (tt) ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (577, 14, NULL, 15, 'Ôn tập', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (579, 13, NULL, 16, 'Unit 8. Viewing The Output (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (580, 13, NULL, 17, 'Unit 9. Choosing A Printer', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (581, 13, NULL, 18, 'Unit 9. Choosing A Printer (continued)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (582, 13, NULL, 19, 'Unit 10. I/O Devices For The Disabled', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (583, 67, NULL, 1, 'Bài 1.Tổng quan về đồ họa', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (584, 67, NULL, 2, 'Bài 2.Lập trình đồ họa với OpenGL', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (585, 67, NULL, 3, 'Bài 3. Kỹ thuật đồ họa 2D', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (586, 67, NULL, 4, 'Bài 4. Kỹ thuật đồ họa 3D', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (587, 67, NULL, 5, 'Bài 5. Biểu diễn đường và mặt cong', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (588, 67, NULL, 6, 'Bài 6.Các kỹ thuật nâng cao', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (589, 67, NULL, 7, 'Bài 7.Hoạt hình ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (590, 67, NULL, 8, 'Bài 8.Thực tại ảo', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (598, 67, NULL, 9, 'Ôn tập', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (599, 69, NULL, 1, 'Bài 1. Tổng quan về quản lý dự án phần mềm', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (600, 69, NULL, 2, 'Bài 2. Các Khái niệm, Thuật ngữ và Định nghĩa', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (601, 69, NULL, 3, 'Bài 3. Người quản lý dự án', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (602, 69, NULL, 4, 'Bài 4. Xem xét dự án như một bức tranh tổng thể', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (603, 69, NULL, 5, 'Bài 5. Quy trình phát triển phần mềm', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (604, 69, NULL, 6, 'Bài 6. Ước lượng phần mềm', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (605, 69, NULL, 7, 'Bài 7. Các kỹ thuật ước lượng dự án ( 4 giờ)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (606, 69, NULL, 8, 'Thi giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (607, 69, NULL, 9, 'Bài 10: Tạo lịch trình và chi phí', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (608, 69, NULL, 10, 'Bài 11. Quản lý thay đổi', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (609, 69, NULL, 11, 'Bài 12. Quản lý rủi ro', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (610, 69, NULL, 12, 'Bài 13. Đo lường phần mềm (4 giờ)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (611, 69, NULL, 13, 'Bài 14: Quản lý con người', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (612, 69, NULL, 14, 'Bài 15. Giám sát và báo cáo dự án', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (618, 3, NULL, 1, 'CHƯƠNG 1. TỔNG QUAN VỀ TIN HỌC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (619, 3, NULL, 2, 'CHƯƠNG 2. NGÔN NGỮ LẬP TRÌNH C', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (620, 3, NULL, 3, 'CHƯƠNG 3. LỆNH NHẬP/ XUẤT DỮ LIỆU', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (621, 3, NULL, 4, 'CHƯƠNG 4. LỆNH ĐIỀU KIỆN', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (622, 3, NULL, 5, 'CHƯƠNG 5. LỆNH LẶP', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (623, 3, NULL, 6, 'CHƯƠNG 5. LỆNH LẶP', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (624, 3, NULL, 7, 'CHƯƠNG 6. HÀM &  CHƯƠNG TRÌNH CON', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (625, 3, NULL, 8, 'CHƯƠNG 6. HÀM & CHƯƠNG TRÌNH CON', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (626, 3, NULL, 9, 'CHƯƠNG 7. KIỂU MẢNG', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (627, 3, NULL, 10, 'CHƯƠNG 8. KIỂU DỮ LIỆU CẤU TRÚC VÀ KIỂU DỮ LIỆU CHUỖI', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (628, 6, NULL, 1, 'BÀI MỞ ĐẦU', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (629, 6, NULL, 2, 'CHƯƠNG 1: TỔNG QUAN VỀ CƠ SỞ DỮ LIỆU', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (630, 6, NULL, 3, 'CHƯƠNG 2: THIẾT KẾ CSDL Ở MỨC LOGIC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (631, 6, NULL, 4, 'CHƯƠNG 3: THIẾT KẾ CƠ SỞ DỮ LIỆU Ở MỨC VẬT LÝ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (632, 6, NULL, 5, 'CHƯƠNG 4: NGÔN NGỮ CƠ SỞ DỮ LIỆU', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (636, 9, NULL, 1, 'Chương 1 - Làm quen với Java và môi trường lập trình Eclipse', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (637, 9, NULL, 2, 'Chương 2- Các thành phần cơ bản và lệnh điều khiển của Java', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (638, 9, NULL, 3, 'Chương 3- Phương thức, mảng và tham chiếu trong Java', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (639, 9, NULL, 4, 'Chương 4 - Lập trình hướng đối tượng với Java', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (640, 9, NULL, 5, 'Ôn tập', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (641, 9, NULL, 6, 'Chương 5 - Xử lý biệt lệ (Exception handling)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (642, 9, NULL, 7, 'Chương 6 - Lập trình giao diện với AWT, Swing và JavaFX (GUI programming)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (643, 9, NULL, 8, 'Chương 7. Lập trình kết nối cơ sở dữ liệu', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (644, 41, NULL, 1, 'CHƯƠNG 1: TỔNG QUAN VỀ HÀNH VI TỔ CHỨC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (645, 41, NULL, 2, 'CHƯƠNG 2: CƠ SỞ CỦA HÀNH VI CÁ NHÂN', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (646, 41, NULL, 3, 'CHƯƠNG 3. TẠO ĐỘNG LỰC CHO CÁ NHÂN TRONG TỔ CHỨC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (647, 41, NULL, 4, 'CHƯƠNG 4: CƠ SỞ HÀNH VI NHÓM', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (648, 41, NULL, 5, 'CHƯƠNG 5: GIAO TIẾP TRONG NHÓM', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (649, 41, NULL, 6, 'CHƯƠNG 6: LÃNH ĐẠO, QUYỀN LỰC VÀ CƠ CẤU TỔ CHỨC TRONG DOANH NGHIỆP', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (650, 41, NULL, 7, 'CHƯƠNG 7: VĂN HÓA TỔ CHỨC, SỰ ĐỔI MỚI VÀ PHÁT TRIỂN', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (651, 44, NULL, 1, 'CHƯƠNG 1: TỔNG QUAN VỀ TMĐT', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (652, 44, NULL, 2, 'CHƯƠNG 1: TỔNG QUAN VỀ TMĐT (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (653, 44, NULL, 3, 'CHƯƠNG 1: TỔNG QUAN VỀ TMĐT (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (654, 44, NULL, 4, 'CHƯƠNG 2: CƠ SỞ HẠ TẦNG TRONG THƯƠNG MẠI ĐIỆN TỬ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (655, 44, NULL, 5, 'CHƯƠNG 2: CƠ SỞ HẠ TẦNG TRONG THƯƠNG MẠI ĐIỆN TỬ (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (656, 44, NULL, 6, 'CHƯƠNG 2: CƠ SỞ HẠ TẦNG TRONG THƯƠNG MẠI ĐIỆN TỬ (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (657, 44, NULL, 7, 'CHƯƠNG 3: CÁC MÔ HÌNH GIAO DỊCH THƯƠNG MẠI ĐIỆN TỬ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (658, 44, NULL, 8, 'CHƯƠNG 3: CÁC MÔ HÌNH GIAO DỊCH THƯƠNG MẠI ĐIỆN TỬ (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (659, 44, NULL, 9, 'CHƯƠNG 4: THANH TOÁN TRONG TMĐT ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (660, 44, NULL, 10, 'CHƯƠNG 4: THANH TOÁN TRONG TMĐT (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (661, 44, NULL, 11, 'CHƯƠNG 5: MARKETING TRONG TMĐT', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (662, 44, NULL, 12, 'CHƯƠNG 6: MARKETING TRONG TMĐT (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (663, 44, NULL, 13, 'CHƯƠNG 7: MARKETING ĐIỆN TỬ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (664, 44, NULL, 14, 'CHƯƠNG 8: AN NINH TRONG TMĐT', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (665, 44, NULL, 15, 'CHƯƠNG 8: AN NINH TRONG TMĐT (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (666, 45, NULL, 1, 'CHƯƠNG 1: KHÁI QUÁT VỀ QUẢN TRỊ NGUỒN NHÂN LỰC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (667, 45, NULL, 2, 'CHƯƠNG 2: PHÂN TÍCH VÀ THIẾT KẾ CÔNG VIỆC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (668, 45, NULL, 3, 'CHƯƠNG 3: KẾ HOẠCH HOÁ NGUỒN NHÂN LỰC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (669, 45, NULL, 4, 'CHƯƠNG 4: THU HÚT VÀ TUYỂN DỤNG NHÂN LỰC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (670, 45, NULL, 5, 'CHƯƠNG 5: ĐÀO TẠO VÀ PHÁT TRIỂN NGUỒN NHÂN LỰC', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (671, 45, NULL, 6, 'Kiểm tra giữa kỳ', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (672, 45, NULL, 7, 'CHƯƠNG 6: TẠO ĐỘNG LỰC LÀM VIỆC CHO NGƯỜI LAO ĐỘNG', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (673, 45, NULL, 8, 'CHƯƠNG 7: ĐÁNH GIÁ & TRẢ CÔNG LAO ĐỘNG', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (674, 45, NULL, 9, 'CHƯƠNG 8: AN TOÀN LAO ĐỘNG', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (675, 45, NULL, 10, 'Ôn tập', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (676, NULL, NULL, 3, NULL, 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (677, NULL, NULL, 3, '', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (678, NULL, NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (679, NULL, NULL, NULL, '', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (680, NULL, NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (681, NULL, NULL, NULL, NULL, 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (682, NULL, NULL, NULL, '4', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (683, NULL, NULL, NULL, '4', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (684, 108, '', 6, 'Bài 4. Kỹ thuật đồ họa 3D (tt)', 1, NULL, NULL);
INSERT INTO `table_hocphan_noidung` VALUES (685, 108, NULL, 4, 'Bài 3. Kỹ thuật đồ họa 2D (tt)', 1, NULL, NULL);

SET FOREIGN_KEY_CHECKS = 1;
